-- =============================================
-- COMPLETE SUPABASE DATABASE SCHEMA
-- Run this entire script in Supabase SQL Editor
-- =============================================

-- Drop existing tables if they exist (to start fresh)
DROP VIEW IF EXISTS admin_daily_statistics CASCADE;
DROP VIEW IF EXISTS admin_gift_code_redemptions CASCADE;
DROP VIEW IF EXISTS admin_investments_with_users CASCADE;
DROP VIEW IF EXISTS admin_referrals_with_users CASCADE;
DROP VIEW IF EXISTS admin_spin_attempts_with_users CASCADE;
DROP VIEW IF EXISTS admin_task_completions_with_users CASCADE;
DROP VIEW IF EXISTS admin_transactions_with_users CASCADE;
DROP VIEW IF EXISTS admin_user_summary CASCADE;
DROP VIEW IF EXISTS daily_stats CASCADE;

DROP TABLE IF EXISTS daily_statistics CASCADE;
DROP TABLE IF EXISTS gift_code_redemptions CASCADE;
DROP TABLE IF EXISTS gift_codes CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS spin_attempts CASCADE;
DROP TABLE IF EXISTS task_completions CASCADE;
DROP TABLE IF EXISTS investments CASCADE;
DROP TABLE IF EXISTS referrals CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS system_settings CASCADE;
DROP TABLE IF EXISTS levels CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- =============================================
-- CORE USER MANAGEMENT
-- =============================================

-- 1. USERS TABLE (Complete user information)
CREATE TABLE users (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Authentication & Basic Info
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(20) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    security_code VARCHAR(10),
    referral_code VARCHAR(20) UNIQUE NOT NULL,
    referred_by UUID REFERENCES users(id),
    
    -- Account Status & Level
    is_active BOOLEAN DEFAULT TRUE,
    current_level INTEGER DEFAULT 0, -- 0=Recruit, 1=Intern, 2=Job1, etc.
    level_upgraded_at TIMESTAMP WITH TIME ZONE,
    level_investment DECIMAL(10,2) DEFAULT 0.00, -- Amount invested in current level
    
    -- Wallets
    income_wallet DECIMAL(15,2) DEFAULT 0.00,
    recharge_wallet DECIMAL(15,2) DEFAULT 0.00,
    main_wallet DECIMAL(15,2) DEFAULT 0.00,
    wealth_fund_balance DECIMAL(15,2) DEFAULT 0.00,
    
    -- Withdrawal Settings
    withdrawal_account_type VARCHAR(20) CHECK (withdrawal_account_type IN ('mpesa', 'till', 'bank')),
    withdrawal_account_details VARCHAR(100),
    withdrawal_password_hash VARCHAR(255),
    
    -- Daily/Period Tracking
    tasks_completed_today INTEGER DEFAULT 0,
    tasks_reset_date DATE DEFAULT CURRENT_DATE,
    yesterday_earnings DECIMAL(10,2) DEFAULT 0.00,
    today_earnings DECIMAL(10,2) DEFAULT 0.00,
    week_earnings DECIMAL(10,2) DEFAULT 0.00,
    month_earnings DECIMAL(10,2) DEFAULT 0.00,
    total_earnings DECIMAL(15,2) DEFAULT 0.00,
    total_withdrawals DECIMAL(15,2) DEFAULT 0.00,
    referral_rebate_total DECIMAL(10,2) DEFAULT 0.00,
    gift_code_earnings DECIMAL(10,2) DEFAULT 0.00,
    
    -- Metadata
    last_login TIMESTAMP WITH TIME ZONE,
    login_count INTEGER DEFAULT 0,
    device_info JSONB,
    ip_address INET
);

-- 2. LEVELS TABLE (Job levels configuration)
CREATE TABLE levels (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    cost DECIMAL(10,2) NOT NULL,
    daily_rate DECIMAL(5,2) NOT NULL,
    tasks_required INTEGER NOT NULL,
    earnings_per_task DECIMAL(8,2) NOT NULL,
    is_locked BOOLEAN DEFAULT FALSE,
    icon VARCHAR(50),
    color VARCHAR(7),
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =============================================
-- FINANCIAL TRANSACTIONS & ACTIVITIES
-- =============================================

-- 3. TRANSACTIONS TABLE (All financial activities)
CREATE TABLE transactions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Transaction Details
    type VARCHAR(30) NOT NULL CHECK (type IN (
        'deposit', 'withdrawal', 'task_earning', 'referral_bonus', 
        'level_upgrade', 'investment', 'investment_return', 'gift_code',
        'spin_win', 'admin_adjustment', 'penalty'
    )),
    amount DECIMAL(15,2) NOT NULL,
    fee DECIMAL(10,2) DEFAULT 0.00,
    net_amount DECIMAL(15,2) NOT NULL,
    
    -- Status & Processing
    status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'failed', 'cancelled')),
    payment_method VARCHAR(30),
    external_reference VARCHAR(100),
    
    -- Metadata
    description TEXT,
    metadata JSONB,
    processed_at TIMESTAMP WITH TIME ZONE,
    admin_notes TEXT
);

-- 4. INVESTMENTS TABLE (Wealth Fund investments)
CREATE TABLE investments (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Investment Details
    bank_name VARCHAR(100) NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    daily_rate DECIMAL(5,2) NOT NULL,
    duration_days INTEGER NOT NULL,
    current_value DECIMAL(15,2) NOT NULL,
    
    -- Status
    status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'completed', 'cancelled')),
    maturity_date DATE NOT NULL,
    withdrawn_at TIMESTAMP WITH TIME ZONE,
    
    -- Metadata
    metadata JSONB
);

-- =============================================
-- TASKS & ACTIVITIES
-- =============================================

-- 5. TASK_COMPLETIONS TABLE (Daily task tracking)
CREATE TABLE task_completions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Task Details
    app_name VARCHAR(100) NOT NULL,
    app_id VARCHAR(50) NOT NULL,
    earnings DECIMAL(8,2) NOT NULL,
    completion_date DATE DEFAULT CURRENT_DATE,
    
    -- Metadata
    install_duration INTEGER,
    metadata JSONB
);

-- 6. SPIN_ATTEMPTS TABLE (Spin to win tracking)
CREATE TABLE spin_attempts (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Spin Details
    prize_won VARCHAR(100),
    prize_value DECIMAL(10,2) DEFAULT 0.00,
    spin_date DATE DEFAULT CURRENT_DATE,
    
    -- Metadata
    metadata JSONB
);

-- =============================================
-- REFERRAL SYSTEM
-- =============================================

-- 7. REFERRALS TABLE (Referral relationships & earnings)
CREATE TABLE referrals (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    referrer_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    referred_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Referral Details
    level INTEGER NOT NULL CHECK (level IN (1, 2, 3)),
    total_earnings DECIMAL(10,2) DEFAULT 0.00,
    last_earning_at TIMESTAMP WITH TIME ZONE,
    
    -- Status
    is_active BOOLEAN DEFAULT TRUE,
    
    UNIQUE(referrer_id, referred_id, level)
);

-- =============================================
-- NOTIFICATIONS & POPUPS SYSTEM
-- =============================================

-- 8. NOTIFICATIONS TABLE (Admin-controlled popups/prompts)
CREATE TABLE notifications (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Targeting
    page_name VARCHAR(50) NOT NULL CHECK (page_name IN (
        'home', 'task', 'upgrade', 'team', 'account', 'wealth_fund',
        'recharge', 'withdraw', 'history', 'spin', 'personal_info',
        'team_reports', 'redeem_gifts', 'help_book', 'all_pages'
    )),
    poster_number INTEGER CHECK (poster_number IN (1, 2, 3)),
    apply_to_levels INTEGER[] DEFAULT '{0,1,2,3,4,5,6}',
    
    -- Status & Type
    is_active BOOLEAN DEFAULT TRUE,
    notification_type VARCHAR(30) DEFAULT 'news' CHECK (notification_type IN (
        'news', 'advertisement', 'warning', 'promotion', 'update', 'maintenance'
    )),
    priority INTEGER DEFAULT 1 CHECK (priority BETWEEN 1 AND 5),
    
    -- Content
    icon VARCHAR(50) DEFAULT 'information-circle',
    heading VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    image_url VARCHAR(500),
    
    -- Buttons
    button1_text VARCHAR(50) DEFAULT 'OK',
    button1_action VARCHAR(100) DEFAULT 'dismiss',
    button2_text VARCHAR(50),
    button2_action VARCHAR(100),
    
    -- Scheduling
    start_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    end_date TIMESTAMP WITH TIME ZONE,
    max_displays INTEGER DEFAULT 1,
    
    -- Metadata
    created_by VARCHAR(100),
    metadata JSONB
);

-- =============================================
-- GIFT CODES & REWARDS
-- =============================================

-- 9. GIFT_CODES TABLE (Admin-generated gift codes)
CREATE TABLE gift_codes (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Code Details
    code VARCHAR(20) UNIQUE NOT NULL,
    reward_type VARCHAR(30) CHECK (reward_type IN ('income_wallet', 'main_wallet', 'both_wallets')),
    income_wallet_amount DECIMAL(10,2) DEFAULT 0.00,
    main_wallet_amount DECIMAL(10,2) DEFAULT 0.00,
    
    -- Usage & Status
    is_active BOOLEAN DEFAULT TRUE,
    max_uses INTEGER DEFAULT 1,
    current_uses INTEGER DEFAULT 0,
    expires_at TIMESTAMP WITH TIME ZONE,
    
    -- Metadata
    description TEXT,
    created_by VARCHAR(100),
    metadata JSONB
);

-- 10. GIFT_CODE_REDEMPTIONS TABLE (Track who redeemed what)
CREATE TABLE gift_code_redemptions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    gift_code_id UUID NOT NULL REFERENCES gift_codes(id) ON DELETE CASCADE,
    redeemed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Reward Given
    income_wallet_reward DECIMAL(10,2) DEFAULT 0.00,
    main_wallet_reward DECIMAL(10,2) DEFAULT 0.00,
    
    UNIQUE(user_id, gift_code_id)
);

-- =============================================
-- SYSTEM CONFIGURATION
-- =============================================

-- 11. SYSTEM_SETTINGS TABLE (App-wide settings)
CREATE TABLE system_settings (
    key VARCHAR(100) PRIMARY KEY,
    value TEXT NOT NULL,
    description TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_by VARCHAR(100)
);

-- 12. DAILY STATISTICS TABLE (persistent daily summaries)
CREATE TABLE daily_statistics (
    stat_date DATE PRIMARY KEY,
    new_users INTEGER DEFAULT 0,
    total_users INTEGER DEFAULT 0,
    total_deposits DECIMAL(15,2) DEFAULT 0.00,
    total_withdrawals DECIMAL(15,2) DEFAULT 0.00,
    active_task_users INTEGER DEFAULT 0,
    total_task_earnings DECIMAL(15,2) DEFAULT 0.00,
    total_referral_earnings DECIMAL(15,2) DEFAULT 0.00,
    total_spin_wins DECIMAL(15,2) DEFAULT 0.00,
    total_gift_code_credits DECIMAL(15,2) DEFAULT 0.00,
    total_investment_volume DECIMAL(15,2) DEFAULT 0.00,
    total_investment_returns DECIMAL(15,2) DEFAULT 0.00,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =============================================
-- INDEXES FOR PERFORMANCE
-- =============================================

-- User indexes
CREATE INDEX idx_users_referral_code ON users(referral_code);
CREATE INDEX idx_users_phone ON users(phone);
CREATE INDEX idx_users_level ON users(current_level);
CREATE INDEX idx_users_status ON users(is_active);

-- Transaction indexes
CREATE INDEX idx_transactions_user_id ON transactions(user_id);
CREATE INDEX idx_transactions_type ON transactions(type);
CREATE INDEX idx_transactions_status ON transactions(status);
CREATE INDEX idx_transactions_created_at ON transactions(created_at);

-- Task completion indexes
CREATE INDEX idx_task_completions_user_date ON task_completions(user_id, completion_date);
CREATE INDEX idx_task_completions_date ON task_completions(completion_date);

-- Referral indexes
CREATE INDEX idx_referrals_referrer ON referrals(referrer_id);
CREATE INDEX idx_referrals_referred ON referrals(referred_id);

-- Notification indexes
CREATE INDEX idx_notifications_page_active ON notifications(page_name, is_active);
CREATE INDEX idx_notifications_active_dates ON notifications(is_active, start_date, end_date);
CREATE INDEX idx_daily_statistics_date ON daily_statistics(stat_date);

-- =============================================
-- INITIAL DATA SETUP
-- =============================================

-- Insert job levels
INSERT INTO levels (id, name, cost, daily_rate, tasks_required, earnings_per_task, icon, color) VALUES
(0, 'Recruit', 0, 0, 0, 10, 'person-add', '#6B7280'),
(1, 'Intern', 800, 1.5, 8, 32, 'school', '#3B82F6'),
(2, 'Job 1', 2000, 2.0, 10, 80, 'briefcase', '#10B981'),
(3, 'Job 2', 6000, 2.5, 12, 240, 'trending-up', '#F59E0B'),
(4, 'Job 3', 15000, 3.0, 15, 1000, 'star', '#EF4444'),
(5, 'Job 4', 40000, 3.5, 18, 2560, 'diamond', '#8B5CF6'),
(6, 'Job 5', 80000, 4.0, 20, 5120, 'trophy', '#EC4899'),
(7, 'Job 6', 200000, 5.0, 25, 20480, 'crown', '#F97316');

-- Insert system settings
INSERT INTO system_settings (key, value, description) VALUES
('whatsapp_customer_care', '+254700000000', 'WhatsApp customer care number'),
('whatsapp_group_link', 'https://chat.whatsapp.com/xxxxx', 'WhatsApp group invitation link'),
('app_maintenance_mode', 'false', 'Enable/disable maintenance mode'),
('withdrawal_fee_percentage', '10', 'Withdrawal fee percentage'),
('referral_level1_percentage', '4', 'Level 1 referral percentage'),
('referral_level2_percentage', '2', 'Level 2 referral percentage'),
('referral_level3_percentage', '0.25', 'Level 3 referral percentage'),
('daily_spin_limit', '3', 'Maximum spins per day per user'),
('task_reset_time', '00:00', 'Time when daily tasks reset');

-- =============================================
-- ADMIN VIEWS WITH USER INFO
-- =============================================

-- View: Transactions with user info
CREATE VIEW admin_transactions_with_users AS
SELECT 
    t.*, 
    u.name AS user_name,
    u.phone AS user_phone,
    u.email AS user_email
FROM transactions t
JOIN users u ON u.id = t.user_id;

-- View: Investments with user info
CREATE VIEW admin_investments_with_users AS
SELECT 
    i.*, 
    u.name AS user_name,
    u.phone AS user_phone,
    u.email AS user_email
FROM investments i
JOIN users u ON u.id = i.user_id;

-- View: Task completions with user info
CREATE VIEW admin_task_completions_with_users AS
SELECT 
    tc.*, 
    u.name AS user_name,
    u.phone AS user_phone,
    u.email AS user_email
FROM task_completions tc
JOIN users u ON u.id = tc.user_id;

-- View: Spin attempts with user info
CREATE VIEW admin_spin_attempts_with_users AS
SELECT 
    sa.*, 
    u.name AS user_name,
    u.phone AS user_phone,
    u.email AS user_email
FROM spin_attempts sa
JOIN users u ON u.id = sa.user_id;

-- View: Gift code redemptions with user info
CREATE VIEW admin_gift_code_redemptions AS
SELECT 
    gcr.*, 
    u.name AS user_name,
    u.phone AS user_phone,
    u.email AS user_email,
    gc.code AS gift_code
FROM gift_code_redemptions gcr
JOIN users u ON u.id = gcr.user_id
JOIN gift_codes gc ON gc.id = gcr.gift_code_id;

-- View: Referrals with referrer & referred info
CREATE VIEW admin_referrals_with_users AS
SELECT 
    r.*, 
    ref.name AS referrer_name,
    ref.phone AS referrer_phone,
    ref.email AS referrer_email,
    referred.name AS referred_name,
    referred.phone AS referred_phone,
    referred.email AS referred_email
FROM referrals r
JOIN users ref ON ref.id = r.referrer_id
JOIN users referred ON referred.id = r.referred_id;

-- View: User Dashboard Summary
CREATE VIEW admin_user_summary AS
SELECT 
    u.id,
    u.name,
    u.email,
    u.phone,
    u.current_level,
    l.name as level_name,
    u.is_active,
    u.income_wallet,
    u.main_wallet,
    u.wealth_fund_balance,
    u.total_earnings,
    u.total_withdrawals,
    u.tasks_completed_today,
    u.created_at as joined_date,
    u.last_login,
    (SELECT COUNT(*) FROM referrals WHERE referrer_id = u.id) as total_referrals
FROM users u
LEFT JOIN levels l ON u.current_level = l.id;

-- View: Daily Statistics (readable with all identifiers)
CREATE VIEW admin_daily_statistics AS
SELECT 
    ds.stat_date,
    ds.new_users,
    ds.total_users,
    ds.total_deposits,
    ds.total_withdrawals,
    ds.active_task_users,
    ds.total_task_earnings,
    ds.total_referral_earnings,
    ds.total_spin_wins,
    ds.total_gift_code_credits,
    ds.total_investment_volume,
    ds.total_investment_returns
FROM daily_statistics ds
ORDER BY ds.stat_date DESC;

-- =============================================
-- ROW LEVEL SECURITY (RLS)
-- =============================================

-- Enable RLS on sensitive tables
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE investments ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_completions ENABLE ROW LEVEL SECURITY;
ALTER TABLE referrals ENABLE ROW LEVEL SECURITY;
ALTER TABLE spin_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE gift_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE gift_code_redemptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE levels ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_settings ENABLE ROW LEVEL SECURITY;

-- Users can only see their own data
CREATE POLICY user_own_data ON users FOR ALL USING (auth.uid() = id);
CREATE POLICY user_own_transactions ON transactions FOR ALL USING (auth.uid() = user_id);
CREATE POLICY user_own_investments ON investments FOR ALL USING (auth.uid() = user_id);
CREATE POLICY user_own_tasks ON task_completions FOR ALL USING (auth.uid() = user_id);

-- Referrals: users can see their referrals
CREATE POLICY user_view_referrals ON referrals
FOR SELECT USING (auth.uid() = referrer_id OR auth.uid() = referred_id);

CREATE POLICY service_manage_referrals ON referrals
FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-- Spin attempts policies
CREATE POLICY user_manage_spin_attempts ON spin_attempts
FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY service_manage_spin_attempts ON spin_attempts
FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-- Gift codes policies (only service role manages)
CREATE POLICY service_manage_gift_codes ON gift_codes
FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-- Gift code redemptions policies
CREATE POLICY user_view_gift_code_redemptions ON gift_code_redemptions
FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY user_insert_gift_code_redemptions ON gift_code_redemptions
FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY service_manage_gift_code_redemptions ON gift_code_redemptions
FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-- Notifications policies
CREATE POLICY public_read_active_notifications ON notifications
FOR SELECT USING (is_active = TRUE);

CREATE POLICY service_manage_notifications ON notifications
FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-- Levels policies
CREATE POLICY public_read_levels ON levels
FOR SELECT USING (TRUE);

CREATE POLICY service_manage_levels ON levels
FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-- System settings policies
CREATE POLICY service_manage_system_settings ON system_settings
FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-- =============================================
-- FUNCTIONS FOR AUTOMATION
-- =============================================

-- Function to generate daily gift codes
CREATE OR REPLACE FUNCTION generate_daily_gift_codes()
RETURNS void AS $$
BEGIN
    -- Generate 10 random gift codes daily
    INSERT INTO gift_codes (code, reward_type, income_wallet_amount, main_wallet_amount, expires_at)
    SELECT 
        'GIFT' || TO_CHAR(NOW(), 'YYYYMMDD') || LPAD((ROW_NUMBER() OVER())::text, 3, '0'),
        'both_wallets',
        (RANDOM() * 100 + 50)::DECIMAL(10,2),
        (RANDOM() * 200 + 100)::DECIMAL(10,2),
        NOW() + INTERVAL '24 hours'
    FROM generate_series(1, 10);
END;
$$ LANGUAGE plpgsql;

-- Function to reset daily tasks
CREATE OR REPLACE FUNCTION reset_daily_tasks()
RETURNS void AS $$
BEGIN
    UPDATE users 
    SET 
        tasks_completed_today = 0,
        tasks_reset_date = CURRENT_DATE,
        yesterday_earnings = today_earnings,
        today_earnings = 0
    WHERE tasks_reset_date < CURRENT_DATE;
END;
$$ LANGUAGE plpgsql;

-- Function to refresh daily statistics
CREATE OR REPLACE FUNCTION refresh_daily_statistics(target_date DATE DEFAULT CURRENT_DATE)
RETURNS void AS $$
BEGIN
    -- Insert or update daily statistics for the target date
    INSERT INTO daily_statistics (
        stat_date,
        new_users,
        total_users,
        total_deposits,
        total_withdrawals,
        active_task_users,
        total_task_earnings,
        total_referral_earnings,
        total_spin_wins,
        total_gift_code_credits,
        total_investment_volume,
        total_investment_returns,
        updated_at
    )
    SELECT 
        target_date,
        -- New users today
        (SELECT COUNT(*) FROM users WHERE DATE(created_at) = target_date),
        -- Total users up to today
        (SELECT COUNT(*) FROM users WHERE DATE(created_at) <= target_date),
        -- Total deposits today
        (SELECT COALESCE(SUM(amount), 2) FROM transactions 
         WHERE type = 'deposit' AND status = 'completed' AND DATE(created_at) = target_date),
        -- Total withdrawals today
        (SELECT COALESCE(SUM(amount), 0) FROM transactions 
         WHERE type = 'withdrawal' AND status = 'completed' AND DATE(created_at) = target_date),
        -- Active task users today
        (SELECT COUNT(DISTINCT user_id) FROM task_completions WHERE completion_date = target_date),
        -- Total task earnings today
        (SELECT COALESCE(SUM(earnings), 0) FROM task_completions WHERE completion_date = target_date),
        -- Total referral earnings today
        (SELECT COALESCE(SUM(amount), 0) FROM transactions 
         WHERE type = 'referral_bonus' AND status = 'completed' AND DATE(created_at) = target_date),
        -- Total spin wins today
        (SELECT COALESCE(SUM(prize_value), 0) FROM spin_attempts WHERE spin_date = target_date),
        -- Total gift code credits today
        (SELECT COALESCE(SUM(income_wallet_reward + main_wallet_reward), 0) 
         FROM gift_code_redemptions WHERE DATE(redeemed_at) = target_date),
        -- Total investment volume today
        (SELECT COALESCE(SUM(amount), 0) FROM investments WHERE DATE(created_at) = target_date),
        -- Total investment returns today
        (SELECT COALESCE(SUM(amount), 0) FROM transactions 
         WHERE type = 'investment_return' AND status = 'completed' AND DATE(created_at) = target_date),
        NOW()
    ON CONFLICT (stat_date) 
    DO UPDATE SET
        new_users = EXCLUDED.new_users,
        total_users = EXCLUDED.total_users,
        total_deposits = EXCLUDED.total_deposits,
        total_withdrawals = EXCLUDED.total_withdrawals,
        active_task_users = EXCLUDED.active_task_users,
        total_task_earnings = EXCLUDED.total_task_earnings,
        total_referral_earnings = EXCLUDED.total_referral_earnings,
        total_spin_wins = EXCLUDED.total_spin_wins,
        total_gift_code_credits = EXCLUDED.total_gift_code_credits,
        total_investment_volume = EXCLUDED.total_investment_volume,
        total_investment_returns = EXCLUDED.total_investment_returns,
        updated_at = NOW();
END;
$$ LANGUAGE plpgsql;

-- Function to ensure daily statistics record exists for current date
CREATE OR REPLACE FUNCTION ensure_daily_statistics_exists()
RETURNS void AS $$
BEGIN
    -- Create today's record if it doesn't exist
    INSERT INTO daily_statistics (stat_date)
    VALUES (CURRENT_DATE)
    ON CONFLICT (stat_date) DO NOTHING;
    
    -- Refresh today's statistics
    PERFORM refresh_daily_statistics(CURRENT_DATE);
END;
$$ LANGUAGE plpgsql;

-- =============================================
-- TRIGGERS FOR AUTOMATION
-- =============================================

-- Update user stats when transactions are added
CREATE OR REPLACE FUNCTION update_user_stats()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.status = 'completed' THEN
        UPDATE users SET
            total_earnings = total_earnings + CASE WHEN NEW.amount > 0 THEN NEW.amount ELSE 0 END,
            total_withdrawals = total_withdrawals + CASE WHEN NEW.type = 'withdrawal' THEN NEW.amount ELSE 0 END,
            today_earnings = today_earnings + CASE WHEN NEW.amount > 0 AND DATE(NEW.created_at) = CURRENT_DATE THEN NEW.amount ELSE 0 END,
            updated_at = NOW()
        WHERE id = NEW.user_id;
        
        -- Refresh daily statistics
        PERFORM ensure_daily_statistics_exists();
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_user_stats
    AFTER INSERT OR UPDATE ON transactions
    FOR EACH ROW EXECUTE FUNCTION update_user_stats();

-- Trigger to refresh daily stats when users are created
CREATE OR REPLACE FUNCTION update_daily_stats_on_user_create()
RETURNS TRIGGER AS $$
BEGIN
    -- Refresh daily statistics when new user joins
    PERFORM ensure_daily_statistics_exists();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_daily_stats_user
    AFTER INSERT ON users
    FOR EACH ROW EXECUTE FUNCTION update_daily_stats_on_user_create();

-- Trigger to refresh daily stats when tasks are completed
CREATE OR REPLACE FUNCTION update_daily_stats_on_task_complete()
RETURNS TRIGGER AS $$
BEGIN
    -- Refresh daily statistics when task is completed
    PERFORM ensure_daily_statistics_exists();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_daily_stats_task
    AFTER INSERT ON task_completions
    FOR EACH ROW EXECUTE FUNCTION update_daily_stats_on_task_complete();

-- Trigger to refresh daily stats when investments are made
CREATE OR REPLACE FUNCTION update_daily_stats_on_investment()
RETURNS TRIGGER AS $$
BEGIN
    -- Refresh daily statistics when investment is made
    PERFORM ensure_daily_statistics_exists();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_daily_stats_investment
    AFTER INSERT ON investments
    FOR EACH ROW EXECUTE FUNCTION update_daily_stats_on_investment();

-- Trigger to refresh daily stats when spins are made
CREATE OR REPLACE FUNCTION update_daily_stats_on_spin()
RETURNS TRIGGER AS $$
BEGIN
    -- Refresh daily statistics when spin is made
    PERFORM ensure_daily_statistics_exists();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_daily_stats_spin
    AFTER INSERT ON spin_attempts
    FOR EACH ROW EXECUTE FUNCTION update_daily_stats_on_spin();

-- Trigger to refresh daily stats when gift codes are redeemed
CREATE OR REPLACE FUNCTION update_daily_stats_on_gift_redeem()
RETURNS TRIGGER AS $$
BEGIN
    -- Refresh daily statistics when gift code is redeemed
    PERFORM ensure_daily_statistics_exists();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_daily_stats_gift
    AFTER INSERT ON gift_code_redemptions
    FOR EACH ROW EXECUTE FUNCTION update_daily_stats_on_gift_redeem();

-- =============================================
-- COMPLETION MESSAGE
-- =============================================

-- Initialize today's daily statistics
SELECT ensure_daily_statistics_exists();

-- Success message
DO $$
BEGIN
    RAISE NOTICE 'Database schema created successfully!';
    RAISE NOTICE 'Tables created: users, levels, transactions, investments, task_completions, spin_attempts, referrals, notifications, gift_codes, gift_code_redemptions, system_settings, daily_statistics';
    RAISE NOTICE 'Admin views created with user name/phone/email for easy identification';
    RAISE NOTICE 'RLS policies enabled for security';
    RAISE NOTICE 'Automation functions and triggers ready';
    RAISE NOTICE 'Daily statistics will auto-update when users join, make transactions, complete tasks, etc.';
    RAISE NOTICE 'Today''s daily statistics record has been initialized!';
END $$;
