-- ====================================================================
-- Gig-Smart: Fresh Supabase project setup (consolidated)
-- Paste this entire file into the new project SQL Editor and Run.
-- Idempotent: safe to re-run. Last edited: 2026-08-15
-- ====================================================================

-- [1/9] Base schema: core tables, views, functions, triggers, RLS
-- ====================================================================
-- =============================================
-- COMPLETE SUPABASE DATABASE SCHEMA
-- Run this entire script in Supabase SQL Editor
-- =============================================

-- Drop existing tables if they exist (to start fresh)
DROP VIEW IF EXISTS admin_daily_statistics CASCADE;
DROP VIEW IF EXISTS admin_gift_code_redemptions CASCADE;
DROP VIEW IF EXISTS admin_investments_with_users CASCADE;
DROP VIEW IF EXISTS admin_referrals_with_users CASCADE;
DROP VIEW IF EXISTS admin_spin_attempts_with_users CASCADE;
DROP VIEW IF EXISTS admin_task_completions_with_users CASCADE;
DROP VIEW IF EXISTS admin_transactions_with_users CASCADE;
DROP VIEW IF EXISTS admin_user_summary CASCADE;
DROP VIEW IF EXISTS daily_stats CASCADE;

DROP TABLE IF EXISTS daily_statistics CASCADE;
DROP TABLE IF EXISTS gift_code_redemptions CASCADE;
DROP TABLE IF EXISTS gift_codes CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS spin_attempts CASCADE;
DROP TABLE IF EXISTS task_completions CASCADE;
DROP TABLE IF EXISTS investments CASCADE;
DROP TABLE IF EXISTS referrals CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS system_settings CASCADE;
DROP TABLE IF EXISTS levels CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- =============================================
-- CORE USER MANAGEMENT
-- =============================================

-- 1. USERS TABLE (Complete user information)
CREATE TABLE users (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Authentication & Basic Info
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(20) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    security_code VARCHAR(10),
    referral_code VARCHAR(20) UNIQUE NOT NULL,
    referred_by UUID REFERENCES users(id),
    
    -- Account Status & Level
    is_active BOOLEAN DEFAULT TRUE,
    current_level INTEGER DEFAULT 0, -- 0=Recruit, 1=Intern, 2=Job1, etc.
    level_upgraded_at TIMESTAMP WITH TIME ZONE,
    level_investment DECIMAL(10,2) DEFAULT 0.00, -- Amount invested in current level
    
    -- Wallets
    income_wallet DECIMAL(15,2) DEFAULT 0.00,
    recharge_wallet DECIMAL(15,2) DEFAULT 0.00,
    main_wallet DECIMAL(15,2) DEFAULT 0.00,
    wealth_fund_balance DECIMAL(15,2) DEFAULT 0.00,
    
    -- Withdrawal Settings
    withdrawal_account_type VARCHAR(20) CHECK (withdrawal_account_type IN ('mpesa', 'till', 'bank')),
    withdrawal_account_details VARCHAR(100),
    withdrawal_password_hash VARCHAR(255),
    
    -- Daily/Period Tracking
    tasks_completed_today INTEGER DEFAULT 0,
    tasks_reset_date DATE DEFAULT CURRENT_DATE,
    yesterday_earnings DECIMAL(10,2) DEFAULT 0.00,
    today_earnings DECIMAL(10,2) DEFAULT 0.00,
    week_earnings DECIMAL(10,2) DEFAULT 0.00,
    month_earnings DECIMAL(10,2) DEFAULT 0.00,
    total_earnings DECIMAL(15,2) DEFAULT 0.00,
    total_withdrawals DECIMAL(15,2) DEFAULT 0.00,
    referral_rebate_total DECIMAL(10,2) DEFAULT 0.00,
    gift_code_earnings DECIMAL(10,2) DEFAULT 0.00,
    
    -- Metadata
    last_login TIMESTAMP WITH TIME ZONE,
    login_count INTEGER DEFAULT 0,
    device_info JSONB,
    ip_address INET,
    real_balance DECIMAL(15,2) DEFAULT 0.00,
    user_category VARCHAR(20) DEFAULT 'new',
    category_updated_at TIMESTAMP WITH TIME ZONE,
    restrictions JSONB DEFAULT '{}'::jsonb
);

-- 2. LEVELS TABLE (Job levels configuration)
CREATE TABLE levels (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    cost DECIMAL(10,2) NOT NULL,
    daily_rate DECIMAL(5,2) NOT NULL,
    tasks_required INTEGER NOT NULL,
    earnings_per_task DECIMAL(8,2) NOT NULL,
    is_locked BOOLEAN DEFAULT FALSE,
    icon VARCHAR(50),
    color VARCHAR(7),
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =============================================
-- FINANCIAL TRANSACTIONS & ACTIVITIES
-- =============================================

-- 3. TRANSACTIONS TABLE (All financial activities)
CREATE TABLE transactions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Transaction Details
    type VARCHAR(30) NOT NULL CHECK (type IN (
        'deposit', 'withdrawal', 'task_earning', 'referral_bonus', 
        'level_upgrade', 'investment', 'investment_return', 'gift_code',
        'spin_win', 'admin_adjustment', 'penalty'
    )),
    amount DECIMAL(15,2) NOT NULL,
    fee DECIMAL(10,2) DEFAULT 0.00,
    net_amount DECIMAL(15,2) NOT NULL,
    
    -- Status & Processing
    status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'failed', 'cancelled')),
    payment_method VARCHAR(30),
    external_reference VARCHAR(100),
    
    -- Metadata
    description TEXT,
    metadata JSONB,
    processed_at TIMESTAMP WITH TIME ZONE,
    admin_notes TEXT
);

-- 4. INVESTMENTS TABLE (Wealth Fund investments)
CREATE TABLE investments (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Investment Details
    bank_name VARCHAR(100) NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    daily_rate DECIMAL(5,2) NOT NULL,
    duration_days INTEGER NOT NULL,
    current_value DECIMAL(15,2) NOT NULL,
    
    -- Status
    status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'completed', 'cancelled')),
    maturity_date DATE NOT NULL,
    withdrawn_at TIMESTAMP WITH TIME ZONE,
    
    -- Metadata
    metadata JSONB
);

-- =============================================
-- TASKS & ACTIVITIES
-- =============================================

-- 5. TASK_COMPLETIONS TABLE (Daily task tracking)
CREATE TABLE task_completions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Task Details
    app_name VARCHAR(100) NOT NULL,
    app_id VARCHAR(50) NOT NULL,
    earnings DECIMAL(8,2) NOT NULL,
    completion_date DATE DEFAULT CURRENT_DATE,
    
    -- Metadata
    install_duration INTEGER,
    metadata JSONB
);

-- 6. SPIN_ATTEMPTS TABLE (Spin to win tracking)
CREATE TABLE spin_attempts (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Spin Details
    prize_won VARCHAR(100),
    prize_value DECIMAL(10,2) DEFAULT 0.00,
    spin_date DATE DEFAULT CURRENT_DATE,
    
    -- Metadata
    metadata JSONB
);

-- =============================================
-- REFERRAL SYSTEM
-- =============================================

-- 7. REFERRALS TABLE (Referral relationships & earnings)
CREATE TABLE referrals (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    referrer_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    referred_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Referral Details
    level INTEGER NOT NULL CHECK (level IN (1, 2, 3)),
    total_earnings DECIMAL(10,2) DEFAULT 0.00,
    last_earning_at TIMESTAMP WITH TIME ZONE,
    
    -- Status
    is_active BOOLEAN DEFAULT TRUE,
    
    UNIQUE(referrer_id, referred_id, level)
);

-- =============================================
-- NOTIFICATIONS & POPUPS SYSTEM
-- =============================================

-- 8. NOTIFICATIONS TABLE (Admin-controlled popups/prompts)
CREATE TABLE notifications (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Targeting
    page_name VARCHAR(50) NOT NULL CHECK (page_name IN (
        'home', 'task', 'upgrade', 'team', 'account', 'wealth_fund',
        'recharge', 'withdraw', 'history', 'spin', 'personal_info',
        'team_reports', 'redeem_gifts', 'help_book', 'all_pages'
    )),
    poster_number INTEGER CHECK (poster_number IN (1, 2, 3)),
    apply_to_levels INTEGER[] DEFAULT '{0,1,2,3,4,5,6}',
    
    -- Status & Type
    is_active BOOLEAN DEFAULT TRUE,
    notification_type VARCHAR(30) DEFAULT 'news' CHECK (notification_type IN (
        'news', 'advertisement', 'warning', 'promotion', 'update', 'maintenance'
    )),
    priority INTEGER DEFAULT 1 CHECK (priority BETWEEN 1 AND 5),
    
    -- Content
    icon VARCHAR(50) DEFAULT 'information-circle',
    heading VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    image_url VARCHAR(500),
    
    -- Buttons
    button1_text VARCHAR(50) DEFAULT 'OK',
    button1_action VARCHAR(100) DEFAULT 'dismiss',
    button2_text VARCHAR(50),
    button2_action VARCHAR(100),
    
    -- Scheduling
    start_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    end_date TIMESTAMP WITH TIME ZONE,
    max_displays INTEGER DEFAULT 1,
    
    -- Metadata
    created_by VARCHAR(100),
    metadata JSONB
);

-- =============================================
-- GIFT CODES & REWARDS
-- =============================================

-- 9. GIFT_CODES TABLE (Admin-generated gift codes)
CREATE TABLE gift_codes (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Code Details
    code VARCHAR(20) UNIQUE NOT NULL,
    reward_type VARCHAR(30) CHECK (reward_type IN ('income_wallet', 'main_wallet', 'both_wallets')),
    income_wallet_amount DECIMAL(10,2) DEFAULT 0.00,
    main_wallet_amount DECIMAL(10,2) DEFAULT 0.00,
    
    -- Usage & Status
    is_active BOOLEAN DEFAULT TRUE,
    max_uses INTEGER DEFAULT 1,
    current_uses INTEGER DEFAULT 0,
    expires_at TIMESTAMP WITH TIME ZONE,
    
    -- Metadata
    description TEXT,
    created_by VARCHAR(100),
    metadata JSONB
);

-- 10. GIFT_CODE_REDEMPTIONS TABLE (Track who redeemed what)
CREATE TABLE gift_code_redemptions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    gift_code_id UUID NOT NULL REFERENCES gift_codes(id) ON DELETE CASCADE,
    redeemed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Reward Given
    income_wallet_reward DECIMAL(10,2) DEFAULT 0.00,
    main_wallet_reward DECIMAL(10,2) DEFAULT 0.00,
    
    UNIQUE(user_id, gift_code_id)
);

-- =============================================
-- SYSTEM CONFIGURATION
-- =============================================

-- 11. SYSTEM_SETTINGS TABLE (App-wide settings)
CREATE TABLE system_settings (
    key VARCHAR(100) PRIMARY KEY,
    value TEXT NOT NULL,
    description TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_by VARCHAR(100)
);

-- 12. DAILY STATISTICS TABLE (persistent daily summaries)
CREATE TABLE daily_statistics (
    stat_date DATE PRIMARY KEY,
    new_users INTEGER DEFAULT 0,
    total_users INTEGER DEFAULT 0,
    total_deposits DECIMAL(15,2) DEFAULT 0.00,
    total_withdrawals DECIMAL(15,2) DEFAULT 0.00,
    active_task_users INTEGER DEFAULT 0,
    total_task_earnings DECIMAL(15,2) DEFAULT 0.00,
    total_referral_earnings DECIMAL(15,2) DEFAULT 0.00,
    total_spin_wins DECIMAL(15,2) DEFAULT 0.00,
    total_gift_code_credits DECIMAL(15,2) DEFAULT 0.00,
    total_investment_volume DECIMAL(15,2) DEFAULT 0.00,
    total_investment_returns DECIMAL(15,2) DEFAULT 0.00,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =============================================
-- INDEXES FOR PERFORMANCE
-- =============================================

-- User indexes
CREATE INDEX idx_users_referral_code ON users(referral_code);
CREATE INDEX idx_users_phone ON users(phone);
CREATE INDEX idx_users_level ON users(current_level);
CREATE INDEX idx_users_status ON users(is_active);

-- Transaction indexes
CREATE INDEX idx_transactions_user_id ON transactions(user_id);
CREATE INDEX idx_transactions_type ON transactions(type);
CREATE INDEX idx_transactions_status ON transactions(status);
CREATE INDEX idx_transactions_created_at ON transactions(created_at);

-- Task completion indexes
CREATE INDEX idx_task_completions_user_date ON task_completions(user_id, completion_date);
CREATE INDEX idx_task_completions_date ON task_completions(completion_date);

-- Referral indexes
CREATE INDEX idx_referrals_referrer ON referrals(referrer_id);
CREATE INDEX idx_referrals_referred ON referrals(referred_id);

-- Notification indexes
CREATE INDEX idx_notifications_page_active ON notifications(page_name, is_active);
CREATE INDEX idx_notifications_active_dates ON notifications(is_active, start_date, end_date);
CREATE INDEX idx_daily_statistics_date ON daily_statistics(stat_date);

-- =============================================
-- INITIAL DATA SETUP
-- =============================================

-- Insert job levels
INSERT INTO levels (id, name, cost, daily_rate, tasks_required, earnings_per_task, icon, color) VALUES
(0, 'Recruit', 0, 0, 0, 10, 'person-add', '#6B7280'),
(1, 'Intern', 800, 1.5, 8, 32, 'school', '#3B82F6'),
(2, 'Job 1', 2000, 2.0, 10, 80, 'briefcase', '#10B981'),
(3, 'Job 2', 6000, 2.5, 12, 240, 'trending-up', '#F59E0B'),
(4, 'Job 3', 15000, 3.0, 15, 1000, 'star', '#EF4444'),
(5, 'Job 4', 40000, 3.5, 18, 2560, 'diamond', '#8B5CF6'),
(6, 'Job 5', 80000, 4.0, 20, 5120, 'trophy', '#EC4899'),
(7, 'Job 6', 200000, 5.0, 25, 20480, 'crown', '#F97316');

-- Insert system settings
INSERT INTO system_settings (key, value, description) VALUES
('whatsapp_customer_care', '+254700000000', 'WhatsApp customer care number'),
('whatsapp_group_link', 'https://chat.whatsapp.com/xxxxx', 'WhatsApp group invitation link'),
('app_maintenance_mode', 'false', 'Enable/disable maintenance mode'),
('withdrawal_fee_percentage', '10', 'Withdrawal fee percentage'),
('referral_level1_percentage', '4', 'Level 1 referral percentage'),
('referral_level2_percentage', '2', 'Level 2 referral percentage'),
('referral_level3_percentage', '0.25', 'Level 3 referral percentage'),
('daily_spin_limit', '3', 'Maximum spins per day per user'),
('task_reset_time', '00:00', 'Time when daily tasks reset');

-- =============================================
-- ADMIN VIEWS WITH USER INFO
-- =============================================

-- View: Transactions with user info
CREATE VIEW admin_transactions_with_users AS
SELECT 
    t.*, 
    u.name AS user_name,
    u.phone AS user_phone,
    u.email AS user_email
FROM transactions t
JOIN users u ON u.id = t.user_id;

-- View: Investments with user info
CREATE VIEW admin_investments_with_users AS
SELECT 
    i.*, 
    u.name AS user_name,
    u.phone AS user_phone,
    u.email AS user_email
FROM investments i
JOIN users u ON u.id = i.user_id;

-- View: Task completions with user info
CREATE VIEW admin_task_completions_with_users AS
SELECT 
    tc.*, 
    u.name AS user_name,
    u.phone AS user_phone,
    u.email AS user_email
FROM task_completions tc
JOIN users u ON u.id = tc.user_id;

-- View: Spin attempts with user info
CREATE VIEW admin_spin_attempts_with_users AS
SELECT 
    sa.*, 
    u.name AS user_name,
    u.phone AS user_phone,
    u.email AS user_email
FROM spin_attempts sa
JOIN users u ON u.id = sa.user_id;

-- View: Gift code redemptions with user info
CREATE VIEW admin_gift_code_redemptions AS
SELECT 
    gcr.*, 
    u.name AS user_name,
    u.phone AS user_phone,
    u.email AS user_email,
    gc.code AS gift_code
FROM gift_code_redemptions gcr
JOIN users u ON u.id = gcr.user_id
JOIN gift_codes gc ON gc.id = gcr.gift_code_id;

-- View: Referrals with referrer & referred info
CREATE VIEW admin_referrals_with_users AS
SELECT 
    r.*, 
    ref.name AS referrer_name,
    ref.phone AS referrer_phone,
    ref.email AS referrer_email,
    referred.name AS referred_name,
    referred.phone AS referred_phone,
    referred.email AS referred_email
FROM referrals r
JOIN users ref ON ref.id = r.referrer_id
JOIN users referred ON referred.id = r.referred_id;

-- View: User Dashboard Summary
CREATE VIEW admin_user_summary AS
SELECT 
    u.id,
    u.name,
    u.email,
    u.phone,
    u.current_level,
    l.name as level_name,
    u.is_active,
    u.income_wallet,
    u.main_wallet,
    u.wealth_fund_balance,
    u.total_earnings,
    u.total_withdrawals,
    u.tasks_completed_today,
    u.created_at as joined_date,
    u.last_login,
    (SELECT COUNT(*) FROM referrals WHERE referrer_id = u.id) as total_referrals
FROM users u
LEFT JOIN levels l ON u.current_level = l.id;

-- View: Daily Statistics (readable with all identifiers)
CREATE VIEW admin_daily_statistics AS
SELECT 
    ds.stat_date,
    ds.new_users,
    ds.total_users,
    ds.total_deposits,
    ds.total_withdrawals,
    ds.active_task_users,
    ds.total_task_earnings,
    ds.total_referral_earnings,
    ds.total_spin_wins,
    ds.total_gift_code_credits,
    ds.total_investment_volume,
    ds.total_investment_returns
FROM daily_statistics ds
ORDER BY ds.stat_date DESC;

-- =============================================
-- ROW LEVEL SECURITY (RLS)
-- =============================================

-- Enable RLS on sensitive tables
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE investments ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_completions ENABLE ROW LEVEL SECURITY;
ALTER TABLE referrals ENABLE ROW LEVEL SECURITY;
ALTER TABLE spin_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE gift_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE gift_code_redemptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE levels ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_settings ENABLE ROW LEVEL SECURITY;

-- Users can only see their own data
CREATE POLICY user_own_data ON users FOR ALL USING (auth.uid() = id);
CREATE POLICY user_own_transactions ON transactions FOR ALL USING (auth.uid() = user_id);
CREATE POLICY user_own_investments ON investments FOR ALL USING (auth.uid() = user_id);
CREATE POLICY user_own_tasks ON task_completions FOR ALL USING (auth.uid() = user_id);

-- Referrals: users can see their referrals
CREATE POLICY user_view_referrals ON referrals
FOR SELECT USING (auth.uid() = referrer_id OR auth.uid() = referred_id);

CREATE POLICY service_manage_referrals ON referrals
FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-- Spin attempts policies
CREATE POLICY user_manage_spin_attempts ON spin_attempts
FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY service_manage_spin_attempts ON spin_attempts
FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-- Gift codes policies (only service role manages)
CREATE POLICY service_manage_gift_codes ON gift_codes
FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-- Gift code redemptions policies
CREATE POLICY user_view_gift_code_redemptions ON gift_code_redemptions
FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY user_insert_gift_code_redemptions ON gift_code_redemptions
FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY service_manage_gift_code_redemptions ON gift_code_redemptions
FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-- Notifications policies
CREATE POLICY public_read_active_notifications ON notifications
FOR SELECT USING (is_active = TRUE);

CREATE POLICY service_manage_notifications ON notifications
FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-- Levels policies
CREATE POLICY public_read_levels ON levels
FOR SELECT USING (TRUE);

CREATE POLICY service_manage_levels ON levels
FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-- System settings policies
CREATE POLICY service_manage_system_settings ON system_settings
FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-- =============================================
-- FUNCTIONS FOR AUTOMATION
-- =============================================

-- Function to generate daily gift codes
CREATE OR REPLACE FUNCTION generate_daily_gift_codes()
RETURNS void AS $$
BEGIN
    -- Generate 10 random gift codes daily
    INSERT INTO gift_codes (code, reward_type, income_wallet_amount, main_wallet_amount, expires_at)
    SELECT 
        'GIFT' || TO_CHAR(NOW(), 'YYYYMMDD') || LPAD((ROW_NUMBER() OVER())::text, 3, '0'),
        'both_wallets',
        (RANDOM() * 100 + 50)::DECIMAL(10,2),
        (RANDOM() * 200 + 100)::DECIMAL(10,2),
        NOW() + INTERVAL '24 hours'
    FROM generate_series(1, 10);
END;
$$ LANGUAGE plpgsql;

-- Function to reset daily tasks
CREATE OR REPLACE FUNCTION reset_daily_tasks()
RETURNS void AS $$
BEGIN
    UPDATE users 
    SET 
        tasks_completed_today = 0,
        tasks_reset_date = CURRENT_DATE,
        yesterday_earnings = today_earnings,
        today_earnings = 0
    WHERE tasks_reset_date < CURRENT_DATE;
END;
$$ LANGUAGE plpgsql;

-- Function to refresh daily statistics
CREATE OR REPLACE FUNCTION refresh_daily_statistics(target_date DATE DEFAULT CURRENT_DATE)
RETURNS void AS $$
BEGIN
    -- Insert or update daily statistics for the target date
    INSERT INTO daily_statistics (
        stat_date,
        new_users,
        total_users,
        total_deposits,
        total_withdrawals,
        active_task_users,
        total_task_earnings,
        total_referral_earnings,
        total_spin_wins,
        total_gift_code_credits,
        total_investment_volume,
        total_investment_returns,
        updated_at
    )
    SELECT 
        target_date,
        -- New users today
        (SELECT COUNT(*) FROM users WHERE DATE(created_at) = target_date),
        -- Total users up to today
        (SELECT COUNT(*) FROM users WHERE DATE(created_at) <= target_date),
        -- Total deposits today
        (SELECT COALESCE(SUM(amount), 2) FROM transactions 
         WHERE type = 'deposit' AND status = 'completed' AND DATE(created_at) = target_date),
        -- Total withdrawals today
        (SELECT COALESCE(SUM(amount), 0) FROM transactions 
         WHERE type = 'withdrawal' AND status = 'completed' AND DATE(created_at) = target_date),
        -- Active task users today
        (SELECT COUNT(DISTINCT user_id) FROM task_completions WHERE completion_date = target_date),
        -- Total task earnings today
        (SELECT COALESCE(SUM(earnings), 0) FROM task_completions WHERE completion_date = target_date),
        -- Total referral earnings today
        (SELECT COALESCE(SUM(amount), 0) FROM transactions 
         WHERE type = 'referral_bonus' AND status = 'completed' AND DATE(created_at) = target_date),
        -- Total spin wins today
        (SELECT COALESCE(SUM(prize_value), 0) FROM spin_attempts WHERE spin_date = target_date),
        -- Total gift code credits today
        (SELECT COALESCE(SUM(income_wallet_reward + main_wallet_reward), 0) 
         FROM gift_code_redemptions WHERE DATE(redeemed_at) = target_date),
        -- Total investment volume today
        (SELECT COALESCE(SUM(amount), 0) FROM investments WHERE DATE(created_at) = target_date),
        -- Total investment returns today
        (SELECT COALESCE(SUM(amount), 0) FROM transactions 
         WHERE type = 'investment_return' AND status = 'completed' AND DATE(created_at) = target_date),
        NOW()
    ON CONFLICT (stat_date) 
    DO UPDATE SET
        new_users = EXCLUDED.new_users,
        total_users = EXCLUDED.total_users,
        total_deposits = EXCLUDED.total_deposits,
        total_withdrawals = EXCLUDED.total_withdrawals,
        active_task_users = EXCLUDED.active_task_users,
        total_task_earnings = EXCLUDED.total_task_earnings,
        total_referral_earnings = EXCLUDED.total_referral_earnings,
        total_spin_wins = EXCLUDED.total_spin_wins,
        total_gift_code_credits = EXCLUDED.total_gift_code_credits,
        total_investment_volume = EXCLUDED.total_investment_volume,
        total_investment_returns = EXCLUDED.total_investment_returns,
        updated_at = NOW();
END;
$$ LANGUAGE plpgsql;

-- Function to ensure daily statistics record exists for current date
CREATE OR REPLACE FUNCTION ensure_daily_statistics_exists()
RETURNS void AS $$
BEGIN
    -- Create today's record if it doesn't exist
    INSERT INTO daily_statistics (stat_date)
    VALUES (CURRENT_DATE)
    ON CONFLICT (stat_date) DO NOTHING;
    
    -- Refresh today's statistics
    PERFORM refresh_daily_statistics(CURRENT_DATE);
END;
$$ LANGUAGE plpgsql;

-- =============================================
-- TRIGGERS FOR AUTOMATION
-- =============================================

-- Update user stats when transactions are added
CREATE OR REPLACE FUNCTION update_user_stats()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.status = 'completed' THEN
        UPDATE users SET
            total_earnings = total_earnings + CASE WHEN NEW.amount > 0 THEN NEW.amount ELSE 0 END,
            total_withdrawals = total_withdrawals + CASE WHEN NEW.type = 'withdrawal' THEN NEW.amount ELSE 0 END,
            today_earnings = today_earnings + CASE WHEN NEW.amount > 0 AND DATE(NEW.created_at) = CURRENT_DATE THEN NEW.amount ELSE 0 END,
            updated_at = NOW()
        WHERE id = NEW.user_id;
        
        -- Refresh daily statistics
        PERFORM ensure_daily_statistics_exists();
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_user_stats
    AFTER INSERT OR UPDATE ON transactions
    FOR EACH ROW EXECUTE FUNCTION update_user_stats();

-- Trigger to refresh daily stats when users are created
CREATE OR REPLACE FUNCTION update_daily_stats_on_user_create()
RETURNS TRIGGER AS $$
BEGIN
    -- Refresh daily statistics when new user joins
    PERFORM ensure_daily_statistics_exists();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_daily_stats_user
    AFTER INSERT ON users
    FOR EACH ROW EXECUTE FUNCTION update_daily_stats_on_user_create();

-- Trigger to refresh daily stats when tasks are completed
CREATE OR REPLACE FUNCTION update_daily_stats_on_task_complete()
RETURNS TRIGGER AS $$
BEGIN
    -- Refresh daily statistics when task is completed
    PERFORM ensure_daily_statistics_exists();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_daily_stats_task
    AFTER INSERT ON task_completions
    FOR EACH ROW EXECUTE FUNCTION update_daily_stats_on_task_complete();

-- Trigger to refresh daily stats when investments are made
CREATE OR REPLACE FUNCTION update_daily_stats_on_investment()
RETURNS TRIGGER AS $$
BEGIN
    -- Refresh daily statistics when investment is made
    PERFORM ensure_daily_statistics_exists();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_daily_stats_investment
    AFTER INSERT ON investments
    FOR EACH ROW EXECUTE FUNCTION update_daily_stats_on_investment();

-- Trigger to refresh daily stats when spins are made
CREATE OR REPLACE FUNCTION update_daily_stats_on_spin()
RETURNS TRIGGER AS $$
BEGIN
    -- Refresh daily statistics when spin is made
    PERFORM ensure_daily_statistics_exists();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_daily_stats_spin
    AFTER INSERT ON spin_attempts
    FOR EACH ROW EXECUTE FUNCTION update_daily_stats_on_spin();

-- Trigger to refresh daily stats when gift codes are redeemed
CREATE OR REPLACE FUNCTION update_daily_stats_on_gift_redeem()
RETURNS TRIGGER AS $$
BEGIN
    -- Refresh daily statistics when gift code is redeemed
    PERFORM ensure_daily_statistics_exists();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_daily_stats_gift
    AFTER INSERT ON gift_code_redemptions
    FOR EACH ROW EXECUTE FUNCTION update_daily_stats_on_gift_redeem();

-- =============================================
-- COMPLETION MESSAGE
-- =============================================

-- Initialize today's daily statistics
SELECT ensure_daily_statistics_exists();

-- Success message
DO $$
BEGIN
    RAISE NOTICE 'Database schema created successfully!';
    RAISE NOTICE 'Tables created: users, levels, transactions, investments, task_completions, spin_attempts, referrals, notifications, gift_codes, gift_code_redemptions, system_settings, daily_statistics';
    RAISE NOTICE 'Admin views created with user name/phone/email for easy identification';
    RAISE NOTICE 'RLS policies enabled for security';
    RAISE NOTICE 'Automation functions and triggers ready';
    RAISE NOTICE 'Daily statistics will auto-update when users join, make transactions, complete tasks, etc.';
    RAISE NOTICE 'Today''s daily statistics record has been initialized!';
END $$;

-- [2/9] Cumulative migration: withdrawal_requests, user_daily_activity, activity_logs, referral_bonus_queue
-- ====================================================================
-- Supabase migration: earnings correctness, withdrawals, referrals, check-ins, monitoring, gift codes, tasks
-- Run in Supabase SQL Editor (idempotent where possible).

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Withdrawal requests
CREATE TABLE IF NOT EXISTS withdrawal_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  amount DECIMAL(15,2) NOT NULL,
  fee DECIMAL(10,2) DEFAULT 0.00,
  net_amount DECIMAL(15,2) NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected','completed','failed')),
  payment_details JSONB,
  payment_method VARCHAR(30) CHECK (payment_method IN ('mpesa', 'airtel_money', 'till', 'paybill', 'bank')),
  withdrawal_account_type TEXT,
  withdrawal_account_details JSONB,
  user_name TEXT,
  user_phone TEXT,
  user_email TEXT,
  metadata JSONB,
  transaction_id UUID REFERENCES transactions(id) ON DELETE SET NULL,
  requested_at TIMESTAMPTZ DEFAULT NOW(),
  processed_at TIMESTAMPTZ,
  processed_by VARCHAR(100),
  admin_notes TEXT,
  rejection_reason TEXT,
  external_reference VARCHAR(100)
);
CREATE INDEX IF NOT EXISTS idx_withdrawal_requests_user ON withdrawal_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_withdrawal_requests_status ON withdrawal_requests(status);

-- Snapshot trigger
CREATE OR REPLACE FUNCTION fn_withdrawal_request_insert_snapshot()
RETURNS trigger AS $$
DECLARE u record;
BEGIN
  SELECT * INTO u FROM users WHERE id = NEW.user_id;
  IF NEW.payment_details IS NULL THEN
    NEW.payment_details := jsonb_build_object(
      'withdrawal_account_type', u.withdrawal_account_type,
      'withdrawal_account_details', u.withdrawal_account_details
    );
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS trg_withdrawal_request_snapshot ON withdrawal_requests;
CREATE TRIGGER trg_withdrawal_request_snapshot
BEFORE INSERT ON withdrawal_requests
FOR EACH ROW
EXECUTE PROCEDURE fn_withdrawal_request_insert_snapshot();

-- Daily check-ins
CREATE TABLE IF NOT EXISTS user_daily_activity (
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  activity_date DATE NOT NULL DEFAULT CURRENT_DATE,
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ip INET,
  device_info JSONB,
  PRIMARY KEY(user_id, activity_date)
);
CREATE INDEX IF NOT EXISTS idx_user_daily_activity_date ON user_daily_activity(activity_date);

CREATE OR REPLACE VIEW user_activity_summary AS
SELECT
  u.id,
  u.name,
  u.phone,
  u.email,
  u.created_at::date AS created_date,
  (CURRENT_DATE - u.created_at::date) AS account_age_days,
  COUNT(uda.activity_date) AS checkins,
  GREATEST(0, (CURRENT_DATE - u.created_at::date) - COUNT(uda.activity_date)) AS days_missed
FROM users u
LEFT JOIN user_daily_activity uda ON uda.user_id = u.id
GROUP BY u.id;

-- Monitoring logs
CREATE TABLE IF NOT EXISTS activity_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL,
  severity TEXT DEFAULT 'info' CHECK (severity IN ('info','warning','critical')),
  details JSONB,
  ip INET,
  device_info JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_activity_logs_user ON activity_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_event ON activity_logs(event_type);

-- Earnings views excluding deposits/recharges/withdrawals
CREATE OR REPLACE VIEW earnings_eligible_transactions AS
SELECT * FROM transactions t
WHERE t.status = 'completed'
  AND t.type IN (
    'task_earning','referral_bonus','investment_return','gift_code','spin_win','admin_adjustment'
  );

CREATE OR REPLACE VIEW user_earnings_by_period AS
SELECT
  user_id,
  SUM(CASE WHEN created_at::date = CURRENT_DATE THEN net_amount ELSE 0 END) AS today_earnings,
  SUM(CASE WHEN created_at::date = CURRENT_DATE - INTERVAL '1 day' THEN net_amount ELSE 0 END) AS yesterday_earnings,
  SUM(CASE WHEN created_at >= date_trunc('week', CURRENT_DATE) THEN net_amount ELSE 0 END) AS week_earnings,
  SUM(CASE WHEN created_at >= date_trunc('month', CURRENT_DATE) THEN net_amount ELSE 0 END) AS month_earnings,
  SUM(net_amount) AS total_earnings
FROM earnings_eligible_transactions
GROUP BY user_id;

-- Gift code earnings view
CREATE OR REPLACE VIEW user_gift_code_earnings AS
SELECT u.id AS user_id, COALESCE(SUM(gcr.income_wallet_reward + gcr.main_wallet_reward), 0) AS gift_code_earnings
FROM users u
LEFT JOIN gift_code_redemptions gcr ON gcr.user_id = u.id
GROUP BY u.id;

-- Task progress today
CREATE OR REPLACE VIEW user_task_progress_today AS
SELECT user_id,
       COUNT(*) AS tasks_done_today,
       SUM(earnings) AS task_earnings_today
FROM task_completions
WHERE completion_date = CURRENT_DATE
GROUP BY user_id;

-- Wealth fund status helper
CREATE OR REPLACE VIEW investments_with_status AS
SELECT *,
  CASE
    WHEN status = 'cancelled' THEN 'cancelled'
    WHEN maturity_date <= CURRENT_DATE THEN 'completed'
    ELSE status
  END AS derived_status
FROM investments;

-- Referral bonuses: recruit gating
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_recruit BOOLEAN DEFAULT TRUE;
CREATE TABLE IF NOT EXISTS referral_bonus_queue (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  referrer_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  referred_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  amount DECIMAL(15,2) NOT NULL,
  level INTEGER NOT NULL DEFAULT 1 CHECK (level BETWEEN 1 AND 3),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  processed_at TIMESTAMPTZ,
  admin_notes TEXT,
  UNIQUE(referrer_id, referred_id, level)
);
CREATE INDEX IF NOT EXISTS idx_referral_bonus_queue_referrer ON referral_bonus_queue(referrer_id);
CREATE INDEX IF NOT EXISTS idx_referral_bonus_queue_status ON referral_bonus_queue(status);

-- Withdrawal requests admin view
CREATE OR REPLACE VIEW admin_withdrawal_requests AS
SELECT wr.id, wr.user_id, wr.created_at, wr.amount, wr.fee, wr.net_amount, wr.status,
       wr.payment_details, wr.payment_method, wr.transaction_id, wr.requested_at,
       wr.processed_at, wr.admin_notes, wr.rejection_reason,
       u.name AS user_name, u.phone AS user_phone, u.email AS user_email,
       u.withdrawal_account_type, u.withdrawal_account_details
FROM withdrawal_requests wr
JOIN users u ON u.id = wr.user_id;

-- Date indexes
CREATE INDEX IF NOT EXISTS idx_transactions_created_date ON transactions(((created_at AT TIME ZONE 'UTC')::date));
CREATE INDEX IF NOT EXISTS idx_task_completions_created_date ON task_completions(((created_at AT TIME ZONE 'UTC')::date));

-- [3/9] latest: notifications (supersedes base), spin_attempts, investment_banks
-- ====================================================================

-- 1. Drop and Recreate Notifications Table
-- =============================================
DROP TABLE IF EXISTS notifications CASCADE;

CREATE TABLE notifications (
    id SERIAL PRIMARY KEY,
    page_name VARCHAR(64) NOT NULL,
    poster_number INTEGER NOT NULL CHECK (poster_number BETWEEN 1 AND 3),
    status BOOLEAN NOT NULL DEFAULT TRUE,
    apply_to_levels INTEGER[] NOT NULL,
    type VARCHAR(32) NOT NULL,
    icon VARCHAR(32) NOT NULL,
    heading VARCHAR(129) NOT NULL,
    content TEXT NOT NULL,
    button_1 VARCHAR(32),
    button_2 VARCHAR(32),
    show_on_startup BOOLEAN DEFAULT FALSE,
    dismissible BOOLEAN DEFAULT TRUE,
    has_image BOOLEAN DEFAULT FALSE,
    image_url TEXT,
    link_url TEXT,
    show_once BOOLEAN DEFAULT FALSE,
    show_for_days INTEGER,
    priority INTEGER DEFAULT 1,
    background_color VARCHAR(16),
    text_color VARCHAR(16),
    border_color VARCHAR(16),
    animation VARCHAR(32),
    expires_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- =============================================
-- 2. Insert Sample Notifications (30 records)
-- =============================================
INSERT INTO notifications (page_name, poster_number, status, apply_to_levels, type, icon, heading, content, button_1, button_2, show_on_startup, dismissible, show_once, show_for_days, priority, background_color, text_color, border_color, animation) VALUES
-- Home (3)
('Home', 1, TRUE, '{1,2,3,4,5,6}', 'news', 'star', 'Welcome!', 'Start your day with new tasks.', 'Ok', 'Later', TRUE, TRUE, FALSE, 1, 1, '#fff', '#000', '#007bff', 'fade'),
('Home', 2, TRUE, '{1,2,3,4,5,6}', 'advertisement', 'gift', 'Invite Friends', 'Earn KES 100 for every referral!', 'Invite', 'Dismiss', FALSE, TRUE, FALSE, 2, 2, '#f8f9fa', '#333', '#28a745', 'slide'),
('Home', 3, TRUE, '{1,2,3,4,5,6}', 'info', 'information-circle', 'Upgrade Now', 'Unlock more tasks and earnings by upgrading your level.', 'Upgrade', 'No thanks', FALSE, TRUE, TRUE, 3, 3, '#fff', '#007bff', '#6c757d', 'bounce'),
-- Task (3)
('Task', 1, TRUE, '{2,3,4,5,6}', 'news', 'checkmark-circle', 'Daily Tasks', 'Complete all tasks to maximize your earnings.', 'Ok', NULL, TRUE, TRUE, FALSE, 1, 1, '#fff', '#000', '#28a745', 'fade'),
('Task', 2, TRUE, '{1,2,3,4,5,6}', 'advertisement', 'gift', 'Spin to Win!', 'Try your luck in the Spin Wheel for extra rewards.', 'Spin Now', 'Later', FALSE, TRUE, FALSE, 1, 2, '#fff', '#000', '#fd7e14', 'slide'),
('Task', 3, TRUE, '{1,2,3,4,5,6}', 'info', 'information-circle', 'Need Help?', 'Check the Help Book for tips on completing tasks.', 'Help Book', NULL, FALSE, TRUE, FALSE, 1, 3, '#fff', '#000', '#007bff', 'bounce'),
-- Upgrade (3)
('Upgrade', 1, TRUE, '{1,2,3,4,5,6}', 'news', 'trending-up-outline', 'Upgrade Offer', 'Special discount on upgrades this week!', 'Upgrade', 'Later', TRUE, TRUE, FALSE, 2, 1, '#fff', '#000', '#28a745', 'fade'),
('Upgrade', 2, TRUE, '{1,2,3,4,5,6}', 'advertisement', 'cash-outline', 'Bonus Earnings', 'Upgrade to J2 and earn double for 7 days.', 'Upgrade', NULL, FALSE, TRUE, FALSE, 2, 2, '#fff', '#000', '#fd7e14', 'slide'),
('Upgrade', 3, TRUE, '{1,2,3,4,5,6}', 'info', 'information-circle', 'Level Comparison', 'See the benefits of each level in the comparison table.', 'View Table', NULL, FALSE, TRUE, FALSE, 2, 3, '#fff', '#000', '#007bff', 'bounce'),
-- Team (3)
('Team', 1, TRUE, '{1,2,3,4,5,6}', 'news', 'people', 'Team Bonus', 'Earn more by building a strong team.', 'Invite', NULL, TRUE, TRUE, FALSE, 3, 1, '#fff', '#000', '#28a745', 'fade'),
('Team', 2, TRUE, '{1,2,3,4,5,6}', 'advertisement', 'gift', 'Referral Bonus', 'Get KES 100 for every friend who joins and upgrades.', 'Invite', 'Dismiss', FALSE, TRUE, FALSE, 3, 2, '#fff', '#000', '#fd7e14', 'slide'),
('Team', 3, TRUE, '{1,2,3,4,5,6}', 'info', 'information-circle', 'Team Reports', 'Check your team''s progress in Team Reports.', 'View', NULL, FALSE, TRUE, FALSE, 3, 3, '#fff', '#000', '#007bff', 'bounce'),
-- Account (3)
('Account', 1, TRUE, '{1,2,3,4,5,6}', 'news', 'wallet-outline', 'Wallet Update', 'Track your income and recharge wallet balances here.', 'Ok', NULL, TRUE, TRUE, FALSE, 4, 1, '#fff', '#000', '#28a745', 'fade'),
('Account', 2, TRUE, '{1,2,3,4,5,6}', 'advertisement', 'cash-outline', 'Withdraw Funds', 'Withdraw your earnings easily and securely.', 'Withdraw', NULL, FALSE, TRUE, FALSE, 4, 2, '#fff', '#000', '#fd7e14', 'slide'),
('Account', 3, TRUE, '{1,2,3,4,5,6}', 'info', 'information-circle', 'Profile Info', 'Keep your personal info up to date.', 'Update', NULL, FALSE, TRUE, FALSE, 4, 3, '#fff', '#000', '#007bff', 'bounce'),
-- Wealth Fund (3)
('WealthFund', 1, TRUE, '{1,2,3,4,5,6}', 'news', 'bank', 'New Investment Options', 'Explore new banks for higher returns.', 'View', NULL, TRUE, TRUE, FALSE, 5, 1, '#fff', '#000', '#28a745', 'fade'),
('WealthFund', 2, TRUE, '{1,2,3,4,5,6}', 'advertisement', 'cash-outline', 'Limited Offer', 'Invest now and get a bonus on your returns.', 'Invest', NULL, FALSE, TRUE, FALSE, 5, 2, '#fff', '#000', '#fd7e14', 'slide'),
('WealthFund', 3, TRUE, '{1,2,3,4,5,6}', 'info', 'information-circle', 'Investment Guide', 'Check our guide for smart investing.', 'Guide', NULL, FALSE, TRUE, FALSE, 5, 3, '#fff', '#000', '#007bff', 'bounce'),
-- Recharge (3)
('Recharge', 1, TRUE, '{1,2,3,4,5,6}', 'news', 'add-circle', 'Recharge Bonus', 'Recharge today and get 5% extra.', 'Recharge', NULL, TRUE, TRUE, FALSE, 6, 1, '#fff', '#000', '#28a745', 'fade'),
('Recharge', 2, TRUE, '{1,2,3,4,5,6}', 'advertisement', 'gift', 'Top-up Offer', 'Top up your wallet and stand a chance to win prizes.', 'Top Up', NULL, FALSE, TRUE, FALSE, 6, 2, '#fff', '#000', '#fd7e14', 'slide'),
('Recharge', 3, TRUE, '{1,2,3,4,5,6}', 'info', 'information-circle', 'Recharge Info', 'Check recharge limits and offers here.', 'Info', NULL, FALSE, TRUE, FALSE, 6, 3, '#fff', '#000', '#007bff', 'bounce'),
-- Withdraw (3)
('Withdrawal', 1, TRUE, '{1,2,3,4,5,6}', 'news', 'arrow-down-circle', 'Withdrawal Info', 'Withdrawals are processed Monday to Friday.', 'Ok', NULL, TRUE, TRUE, FALSE, 7, 1, '#fff', '#000', '#28a745', 'fade'),
('Withdrawal', 2, TRUE, '{1,2,3,4,5,6}', 'advertisement', 'gift', 'Withdraw Bonus', 'Withdraw KES 10,000+ to get a bonus entry in Spin Wheel.', 'Spin Now', NULL, FALSE, TRUE, FALSE, 7, 2, '#fff', '#000', '#fd7e14', 'slide'),
('Withdrawal', 3, TRUE, '{1,2,3,4,5,6}', 'info', 'information-circle', 'Withdrawal Guide', 'See our withdrawal guide for tips.', 'Guide', NULL, FALSE, TRUE, FALSE, 7, 3, '#fff', '#000', '#007bff', 'bounce'),
-- SpinWheel (3)
('SpinWheel', 1, TRUE, '{1,2,3,4,5,6}', 'news', 'refresh-circle', 'Spin to Win', 'Try your luck every day for big rewards!', 'Spin', NULL, TRUE, TRUE, FALSE, 8, 1, '#fff', '#000', '#28a745', 'fade'),
('SpinWheel', 2, TRUE, '{1,2,3,4,5,6}', 'advertisement', 'gift', 'Spin Offer', 'Get a free spin after every 3 spins.', 'Spin Now', NULL, FALSE, TRUE, FALSE, 8, 2, '#fff', '#000', '#fd7e14', 'slide'),
('SpinWheel', 3, TRUE, '{1,2,3,4,5,6}', 'info', 'information-circle', 'Spin Rules', 'Read the rules before spinning.', 'Rules', NULL, FALSE, TRUE, FALSE, 8, 3, '#fff', '#000', '#007bff', 'bounce');

-- =============================================
-- 3. Create Spin Attempts Table
-- =============================================
CREATE TABLE IF NOT EXISTS spin_attempts (
    id SERIAL PRIMARY KEY,
    user_id UUID NOT NULL,
    bet_amount INTEGER NOT NULL,
    result INTEGER NOT NULL,
    is_win BOOLEAN NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

-- =============================================
-- 4. Create Investment Banks Table
-- =============================================
CREATE TABLE IF NOT EXISTS investment_banks (
    id SERIAL PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    rate NUMERIC(5,2) NOT NULL,
    days INTEGER NOT NULL,
    min_amount INTEGER NOT NULL,
    description TEXT,
    color VARCHAR(16)
);

-- =============================================
-- 5. Insert Sample Investment Banks (15 records)
-- =============================================
INSERT INTO investment_banks (name, rate, days, min_amount, description, color) VALUES
('Thames Royal Bank', 0.20, 7, 500, 'Low risk, short term investment', '#007bff'),
('Barcliff Trust Bank', 0.50, 14, 1000, 'Balanced risk and return profile', '#28a745'),
('Mersey Crown Bank', 0.80, 21, 2000, 'Medium risk, medium term investment', '#ffc107'),
('Edinburgh Capital Bank', 1.50, 30, 5000, 'Higher risk with attractive returns', '#dc3545'),
('Windsor Elite Bank', 2.00, 45, 10000, 'Premium investment option', '#6f42c1'),
('Liverpool Sovereign Bank', 3.00, 60, 20000, 'Maximum return investment package', '#fd7e14'),
('Kenya Growth Fund', 1.00, 30, 3000, 'Local growth investment', '#1e88e5'),
('Nairobi Secure Fund', 0.60, 14, 1500, 'Secure and stable returns', '#43a047'),
('Africa Opportunity Trust', 2.50, 60, 25000, 'High growth African markets', '#fbc02d'),
('Global Wealth Partners', 1.80, 21, 4000, 'International diversified fund', '#1976d2'),
('Emerging Markets Bank', 2.20, 45, 12000, 'Emerging market focus', '#8e24aa'),
('Prime Investors Ltd.', 1.30, 30, 3500, 'Prime investment for steady returns', '#c62828'),
('Diamond Capital', 2.80, 60, 30000, 'Diamond-grade returns', '#ad1457'),
('Savannah Investment', 1.10, 14, 2000, 'Savannah region special', '#388e3c'),
('Safari Wealth Bank', 2.60, 21, 7000, 'Safari themed high yield', '#fbc02d');

-- =============================================
-- 6. Update Levels Table (if needed)
-- =============================================
-- This assumes you already have a levels table
-- If not, you'll need to create it with appropriate columns
-- ALTER TABLE levels ADD COLUMN IF NOT EXISTS is_locked BOOLEAN DEFAULT FALSE;
-- ALTER TABLE levels ADD COLUMN IF NOT EXISTS tasks_required INTEGER DEFAULT 0;
-- [4/9] withdrawal_enhancements: kenyan_banks + withdrawal request columns/RLS
-- ====================================================================
-- =============================================
-- WITHDRAWAL SYSTEM ENHANCEMENTS
-- Run this SQL to add withdrawal request tracking and payment details
-- =============================================

-- 1. Add withdrawal requests table for approval workflow
CREATE TABLE IF NOT EXISTS withdrawal_requests (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Request Details
    amount DECIMAL(15,2) NOT NULL,
    fee DECIMAL(10,2) NOT NULL,
    net_amount DECIMAL(15,2) NOT NULL,
    
    -- Status & Processing
    status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'completed', 'failed')),
    processed_at TIMESTAMP WITH TIME ZONE,
    processed_by VARCHAR(100),
    
    -- Payment Details (from user's withdrawal account)
    payment_method VARCHAR(30) NOT NULL CHECK (payment_method IN ('mpesa', 'airtel_money', 'till', 'paybill', 'bank')),
    payment_details JSONB NOT NULL, -- Store all payment info as JSON
    
    -- Admin Notes
    admin_notes TEXT,
    rejection_reason TEXT,
    
    -- Reference
    transaction_id UUID REFERENCES transactions(id),
    external_reference VARCHAR(100)
);

-- 2. Add Kenyan banks reference table
CREATE TABLE IF NOT EXISTS kenyan_banks (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(10) NOT NULL UNIQUE,
    paybill_number VARCHAR(20),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Update users table to store detailed withdrawal account info
ALTER TABLE users ADD COLUMN IF NOT EXISTS withdrawal_account_details JSONB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS withdrawal_account_verified BOOLEAN DEFAULT FALSE;

-- Insert Kenyan banks data
INSERT INTO kenyan_banks (name, code, paybill_number) VALUES
('Kenya Commercial Bank (KCB)', 'KCB', '522522'),
('Equity Bank', 'EQUITY', '247247'),
('Cooperative Bank', 'COOP', '400200'),
('NCBA Bank', 'NCBA', '228228'),
('Absa Bank Kenya', 'ABSA', '303030'),
('Standard Chartered Bank', 'SCB', '329329'),
('Diamond Trust Bank (DTB)', 'DTB', '521325'),
('I&M Bank', 'I&M', '141414'),
('Stanbic Bank', 'STANBIC', '909090'),
('Family Bank', 'FAMILY', '222111'),
('Sidian Bank', 'SIDIAN', '323232'),
('Bank of Africa', 'BOA', '888880'),
('Prime Bank', 'PRIME', '525252'),
('Gulf African Bank', 'GAB', '444222'),
('Credit Bank', 'CREDIT', '555666')
ON CONFLICT (code) DO NOTHING;

-- 4. Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_withdrawal_requests_user_id ON withdrawal_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_withdrawal_requests_status ON withdrawal_requests(status);
CREATE INDEX IF NOT EXISTS idx_withdrawal_requests_created_at ON withdrawal_requests(created_at);
CREATE INDEX IF NOT EXISTS idx_kenyan_banks_active ON kenyan_banks(is_active);

-- 5. Enable RLS for withdrawal requests
ALTER TABLE withdrawal_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE kenyan_banks ENABLE ROW LEVEL SECURITY;

-- 6. Create RLS policies
CREATE POLICY user_own_withdrawal_requests ON withdrawal_requests
FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY service_manage_withdrawal_requests ON withdrawal_requests
FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

CREATE POLICY public_read_active_banks ON kenyan_banks
FOR SELECT USING (is_active = TRUE);

CREATE POLICY service_manage_banks ON kenyan_banks
FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-- 7. Create admin view for withdrawal requests with user info
DROP VIEW IF EXISTS admin_withdrawal_requests;
CREATE VIEW admin_withdrawal_requests AS
SELECT 
    wr.id,
    wr.user_id,
    wr.created_at,
    wr.amount,
    wr.fee,
    wr.net_amount,
    wr.status,
    wr.payment_details,
    wr.payment_method,
    wr.transaction_id,
    wr.requested_at,
    wr.processed_at,
    wr.admin_notes,
    wr.rejection_reason,
    u.name AS user_name,
    u.phone AS user_phone,
    u.email AS user_email,
    u.current_level,
    l.name AS level_name
FROM withdrawal_requests wr
JOIN users u ON u.id = wr.user_id
LEFT JOIN levels l ON u.current_level = l.id
ORDER BY wr.created_at DESC;

-- 8. Function to create withdrawal request
CREATE OR REPLACE FUNCTION create_withdrawal_request(
    p_user_id UUID,
    p_amount DECIMAL(15,2),
    p_fee DECIMAL(10,2),
    p_payment_method VARCHAR(30),
    p_payment_details JSONB
)
RETURNS UUID AS $$
DECLARE
    v_request_id UUID;
    v_net_amount DECIMAL(15,2);
BEGIN
    v_net_amount := p_amount - p_fee;
    
    -- Insert withdrawal request
    INSERT INTO withdrawal_requests (
        user_id,
        amount,
        fee,
        net_amount,
        payment_method,
        payment_details
    )
    VALUES (
        p_user_id,
        p_amount,
        p_fee,
        v_net_amount,
        p_payment_method,
        p_payment_details
    )
    RETURNING id INTO v_request_id;
    
    -- Create pending transaction
    INSERT INTO transactions (
        user_id,
        type,
        amount,
        fee,
        net_amount,
        status,
        description,
        metadata
    )
    VALUES (
        p_user_id,
        'withdrawal',
        p_amount,
        p_fee,
        v_net_amount,
        'pending',
        'Withdrawal request - pending approval',
        jsonb_build_object(
            'withdrawal_request_id', v_request_id,
            'payment_method', p_payment_method,
            'payment_details', p_payment_details
        )
    );
    
    RETURN v_request_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 9. Update daily statistics to include withdrawal requests
CREATE OR REPLACE FUNCTION refresh_daily_statistics(target_date DATE DEFAULT CURRENT_DATE)
RETURNS void AS $$
BEGIN
    INSERT INTO daily_statistics (
        stat_date,
        new_users,
        total_users,
        total_deposits,
        total_withdrawals,
        active_task_users,
        total_task_earnings,
        total_referral_earnings,
        total_spin_wins,
        total_gift_code_credits,
        total_investment_volume,
        total_investment_returns,
        updated_at
    )
    SELECT 
        target_date,
        (SELECT COUNT(*) FROM users WHERE DATE(created_at) = target_date),
        (SELECT COUNT(*) FROM users WHERE DATE(created_at) <= target_date),
        (SELECT COALESCE(SUM(amount), 0) FROM transactions WHERE type = 'deposit' AND status = 'completed' AND DATE(created_at) = target_date),
        (SELECT COALESCE(SUM(amount), 0) FROM withdrawal_requests WHERE status IN ('completed', 'approved') AND DATE(created_at) = target_date),
        (SELECT COUNT(DISTINCT user_id) FROM task_completions WHERE completion_date = target_date),
        (SELECT COALESCE(SUM(earnings), 0) FROM task_completions WHERE completion_date = target_date),
        (SELECT COALESCE(SUM(amount), 0) FROM transactions WHERE type = 'referral_bonus' AND status = 'completed' AND DATE(created_at) = target_date),
        (SELECT COALESCE(SUM(prize_value), 0) FROM spin_attempts WHERE spin_date = target_date),
        (SELECT COALESCE(SUM(income_wallet_reward + main_wallet_reward), 0) FROM gift_code_redemptions WHERE DATE(redeemed_at) = target_date),
        (SELECT COALESCE(SUM(amount), 0) FROM investments WHERE DATE(created_at) = target_date),
        (SELECT COALESCE(SUM(amount), 0) FROM transactions WHERE type = 'investment_return' AND status = 'completed' AND DATE(created_at) = target_date),
        NOW()
    ON CONFLICT (stat_date)
    DO UPDATE SET
        new_users = EXCLUDED.new_users,
        total_users = EXCLUDED.total_users,
        total_deposits = EXCLUDED.total_deposits,
        total_withdrawals = EXCLUDED.total_withdrawals,
        active_task_users = EXCLUDED.active_task_users,
        total_task_earnings = EXCLUDED.total_task_earnings,
        total_referral_earnings = EXCLUDED.total_referral_earnings,
        total_spin_wins = EXCLUDED.total_spin_wins,
        total_gift_code_credits = EXCLUDED.total_gift_code_credits,
        total_investment_volume = EXCLUDED.total_investment_volume,
        total_investment_returns = EXCLUDED.total_investment_returns,
        updated_at = NOW();
END;
$$ LANGUAGE plpgsql;

-- Success message
DO $$
BEGIN
    RAISE NOTICE 'Withdrawal system enhancements completed successfully!';
    RAISE NOTICE 'Added: withdrawal_requests table, kenyan_banks table, admin views';
    RAISE NOTICE 'Enhanced: users table with detailed withdrawal account info';
    RAISE NOTICE 'Created: withdrawal request creation function';
END $$;

-- [5/9] safe_migration_additions: earnings views (user_earnings_by_period, user_gift_code_earnings)
-- ====================================================================
-- Safe migration additions - only creates what doesn't exist
-- Run this after create_missing_tables.sql

-- Create extension if not exists
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Create views that don't exist or recreate with correct column names
-- Earnings eligible transactions view
CREATE OR REPLACE VIEW earnings_eligible_transactions AS
SELECT * FROM transactions t
WHERE t.status = 'completed'
  AND t.type IN (
    'task_earning','referral_bonus','investment_return','gift_code','spin_win','admin_adjustment'
  );

-- User earnings by period view
CREATE OR REPLACE VIEW user_earnings_by_period AS
SELECT
  user_id,
  SUM(CASE WHEN created_at::date = CURRENT_DATE THEN net_amount ELSE 0 END) AS today_earnings,
  SUM(CASE WHEN created_at::date = CURRENT_DATE - INTERVAL '1 day' THEN net_amount ELSE 0 END) AS yesterday_earnings,
  SUM(CASE WHEN created_at >= date_trunc('week', CURRENT_DATE) THEN net_amount ELSE 0 END) AS week_earnings,
  SUM(CASE WHEN created_at >= date_trunc('month', CURRENT_DATE) THEN net_amount ELSE 0 END) AS month_earnings,
  SUM(net_amount) AS total_earnings
FROM earnings_eligible_transactions
GROUP BY user_id;

-- Gift code earnings view
CREATE OR REPLACE VIEW user_gift_code_earnings AS
SELECT u.id AS user_id, COALESCE(SUM(gcr.income_wallet_reward + gcr.main_wallet_reward), 0) AS gift_code_earnings
FROM users u
LEFT JOIN gift_code_redemptions gcr ON gcr.user_id = u.id
GROUP BY u.id;

-- Task progress today view (fixed column names)
DROP VIEW IF EXISTS user_task_progress_today;
CREATE OR REPLACE VIEW user_task_progress_today AS
SELECT 
  user_id,
  COUNT(*) AS completed_tasks,
  SUM(earnings) AS today_earnings
FROM task_completions
WHERE created_at::date = CURRENT_DATE
GROUP BY user_id;

-- Investments with status view
CREATE OR REPLACE VIEW investments_with_status AS
SELECT *,
  CASE
    WHEN status = 'cancelled' THEN 'cancelled'
    WHEN maturity_date <= CURRENT_DATE THEN 'completed'
    ELSE status
  END AS derived_status
FROM investments;

-- Add missing columns to withdrawal_requests if needed
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name = 'withdrawal_requests' AND column_name = 'requested_at') THEN
        ALTER TABLE withdrawal_requests ADD COLUMN requested_at TIMESTAMPTZ DEFAULT NOW();
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name = 'withdrawal_requests' AND column_name = 'processed_at') THEN
        ALTER TABLE withdrawal_requests ADD COLUMN processed_at TIMESTAMPTZ;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name = 'withdrawal_requests' AND column_name = 'admin_notes') THEN
        ALTER TABLE withdrawal_requests ADD COLUMN admin_notes TEXT;
    END IF;
END $$;

-- Create admin withdrawal requests view safely
DROP VIEW IF EXISTS admin_withdrawal_requests;
CREATE VIEW admin_withdrawal_requests AS
SELECT 
  wr.id,
  wr.user_id,
  wr.amount,
  wr.fee,
  wr.net_amount,
  wr.status,
  wr.payment_details,
  wr.transaction_id,
  COALESCE(wr.requested_at, wr.created_at, NOW()) AS requested_at,
  wr.processed_at,
  wr.admin_notes,
  u.name AS user_name,
  u.phone AS user_phone,
  u.email AS user_email,
  u.withdrawal_account_type,
  u.withdrawal_account_details
FROM withdrawal_requests wr
JOIN users u ON u.id = wr.user_id;

-- Create indexes for performance (removed function-based indexes that cause errors)
CREATE INDEX IF NOT EXISTS idx_transactions_created_at ON transactions(created_at);
CREATE INDEX IF NOT EXISTS idx_task_completions_created_at ON task_completions(created_at);
CREATE INDEX IF NOT EXISTS idx_transactions_user_type ON transactions(user_id, type);
CREATE INDEX IF NOT EXISTS idx_withdrawal_requests_user ON withdrawal_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_withdrawal_requests_status ON withdrawal_requests(status);
CREATE INDEX IF NOT EXISTS idx_user_daily_activity_date ON user_daily_activity(activity_date);
CREATE INDEX IF NOT EXISTS idx_activity_logs_created_at ON activity_logs(created_at);
DO $$
BEGIN
  IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'suspicious_activity') THEN
    CREATE INDEX IF NOT EXISTS idx_suspicious_activity_created_at ON suspicious_activity(created_at);
  END IF;
END $$;

-- Add is_recruit column to users if not exists
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_recruit BOOLEAN DEFAULT TRUE;

-- [6/9] create_missing_tables: suspicious_activity + column backfills
-- ====================================================================
-- Create missing tables for the new features
-- Run this if you get "relation does not exist" errors

-- Create referral_bonus_queue table
CREATE TABLE IF NOT EXISTS referral_bonus_queue (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  referrer_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  referred_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  amount DECIMAL(15,2) NOT NULL,
  level INTEGER NOT NULL DEFAULT 1 CHECK (level BETWEEN 1 AND 3),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected','pending-review')),
  is_recruit BOOLEAN DEFAULT TRUE,
  is_suspicious BOOLEAN DEFAULT FALSE,
  risk_score INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  processed_at TIMESTAMPTZ,
  admin_notes TEXT,
  UNIQUE(referrer_id, referred_id, level)
);

CREATE INDEX IF NOT EXISTS idx_referral_bonus_queue_referrer ON referral_bonus_queue(referrer_id);
CREATE INDEX IF NOT EXISTS idx_referral_bonus_queue_status ON referral_bonus_queue(status);

-- Create suspicious_activity table for bot monitoring
CREATE TABLE IF NOT EXISTS suspicious_activity (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  activity_type TEXT NOT NULL,
  description TEXT,
  risk_score INTEGER DEFAULT 0 CHECK (risk_score BETWEEN 0 AND 100),
  ip_address INET,
  user_agent TEXT,
  metadata JSONB,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending','reviewed','false_positive')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  reviewed_at TIMESTAMPTZ,
  reviewed_by UUID REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_suspicious_activity_user ON suspicious_activity(user_id);
CREATE INDEX IF NOT EXISTS idx_suspicious_activity_status ON suspicious_activity(status);
CREATE INDEX IF NOT EXISTS idx_suspicious_activity_risk ON suspicious_activity(risk_score);

-- Create activity_logs table for comprehensive logging
CREATE TABLE IF NOT EXISTS activity_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL,
  severity TEXT DEFAULT 'info' CHECK (severity IN ('info','warning','critical')),
  details JSONB,
  ip INET,
  device_info JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_activity_logs_user ON activity_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_event ON activity_logs(event_type);
CREATE INDEX IF NOT EXISTS idx_activity_logs_created ON activity_logs(created_at);

-- Create user_daily_activity table for daily check-ins
CREATE TABLE IF NOT EXISTS user_daily_activity (
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  activity_date DATE NOT NULL DEFAULT CURRENT_DATE,
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ip INET,
  device_info JSONB,
  PRIMARY KEY (user_id, activity_date)
);

CREATE INDEX IF NOT EXISTS idx_user_daily_activity_date ON user_daily_activity(activity_date);

-- Add missing columns to users table if they don't exist
DO $$
BEGIN
    -- Check and add is_recruit column
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name = 'users' AND column_name = 'is_recruit') THEN
        ALTER TABLE users ADD COLUMN is_recruit BOOLEAN DEFAULT TRUE;
    END IF;
    
    -- Check and add tasks_reset_date column
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name = 'users' AND column_name = 'tasks_reset_date') THEN
        ALTER TABLE users ADD COLUMN tasks_reset_date DATE DEFAULT CURRENT_DATE;
    END IF;
    
    -- Check and add yesterday_earnings column
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name = 'users' AND column_name = 'yesterday_earnings') THEN
        ALTER TABLE users ADD COLUMN yesterday_earnings DECIMAL(15,2) DEFAULT 0.00;
    END IF;
END $$;

-- Create user_activity_summary view
CREATE OR REPLACE VIEW user_activity_summary AS
SELECT
  u.id,
  u.name,
  u.phone,
  u.email,
  u.created_at::date AS created_date,
  (CURRENT_DATE - u.created_at::date) AS account_age_days,
  COUNT(uda.activity_date) AS checkins,
  GREATEST(0, (CURRENT_DATE - u.created_at::date) - COUNT(uda.activity_date)) AS days_missed
FROM users u
LEFT JOIN user_daily_activity uda ON uda.user_id = u.id
GROUP BY u.id;

-- [7/9] fix_view_columns: view column fixes
-- ====================================================================
-- Fix for view column name mismatch
-- Run this after the main migration if you get column name errors

-- First, ensure the withdrawal_requests table has all required columns
DO $$
BEGIN
    -- Add missing columns if they don't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name = 'withdrawal_requests' AND column_name = 'requested_at') THEN
        ALTER TABLE withdrawal_requests ADD COLUMN requested_at TIMESTAMPTZ DEFAULT NOW();
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name = 'withdrawal_requests' AND column_name = 'processed_at') THEN
        ALTER TABLE withdrawal_requests ADD COLUMN processed_at TIMESTAMPTZ;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name = 'withdrawal_requests' AND column_name = 'admin_notes') THEN
        ALTER TABLE withdrawal_requests ADD COLUMN admin_notes TEXT;
    END IF;
END $$;

-- Drop and recreate admin_withdrawal_requests view with correct column names
DROP VIEW IF EXISTS admin_withdrawal_requests;

-- First check what columns actually exist in withdrawal_requests
-- Use created_at as fallback if requested_at doesn't exist
CREATE OR REPLACE VIEW admin_withdrawal_requests AS
SELECT 
  wr.id,
  wr.user_id,
  wr.amount,
  wr.fee,
  wr.net_amount,
  wr.status,
  wr.payment_details,
  wr.transaction_id,
  COALESCE(wr.requested_at, wr.created_at, NOW()) AS requested_at,
  wr.processed_at,
  wr.admin_notes,
  u.name AS user_name, 
  u.phone AS user_phone, 
  u.email AS user_email,
  u.withdrawal_account_type, 
  u.withdrawal_account_details
FROM withdrawal_requests wr
JOIN users u ON u.id = wr.user_id;

-- Also fix user_task_progress_today view (column name mismatch)
DROP VIEW IF EXISTS user_task_progress_today;

CREATE OR REPLACE VIEW user_task_progress_today AS
SELECT 
  user_id,
  COUNT(*) AS completed_tasks,
  SUM(earnings) AS today_earnings
FROM task_completions
WHERE created_at::date = CURRENT_DATE
GROUP BY user_id;

-- Add missing columns to users table if they don't exist
ALTER TABLE users 
ADD COLUMN IF NOT EXISTS tasks_reset_date DATE,
ADD COLUMN IF NOT EXISTS yesterday_earnings DECIMAL(15,2) DEFAULT 0.00;

-- Create suspicious_activity table for bot monitoring
CREATE TABLE IF NOT EXISTS suspicious_activity (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  activity_type TEXT NOT NULL,
  description TEXT,
  risk_score INTEGER DEFAULT 0 CHECK (risk_score BETWEEN 0 AND 100),
  ip_address INET,
  user_agent TEXT,
  metadata JSONB,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending','reviewed','false_positive')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  reviewed_at TIMESTAMPTZ,
  reviewed_by UUID REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_suspicious_activity_user ON suspicious_activity(user_id);
CREATE INDEX IF NOT EXISTS idx_suspicious_activity_status ON suspicious_activity(status);
CREATE INDEX IF NOT EXISTS idx_suspicious_activity_risk ON suspicious_activity(risk_score);

-- Add missing columns to referral_bonus_queue
ALTER TABLE referral_bonus_queue 
ADD COLUMN IF NOT EXISTS is_recruit BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS is_suspicious BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS risk_score INTEGER DEFAULT 0;

-- [8/9] payment_system_setup: payment_callbacks, activation_payments
-- ====================================================================
-- Payment System Setup for Gig-Smart
-- Run this SQL in your Supabase SQL Editor

-- 1. Create payment_callbacks table to store all payment webhook data
CREATE TABLE IF NOT EXISTS payment_callbacks (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    external_reference TEXT NOT NULL,
    callback_data JSONB,
    status TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add indexes for better performance
CREATE INDEX IF NOT EXISTS idx_payment_callbacks_external_ref ON payment_callbacks(external_reference);
CREATE INDEX IF NOT EXISTS idx_payment_callbacks_status ON payment_callbacks(status);
CREATE INDEX IF NOT EXISTS idx_payment_callbacks_created_at ON payment_callbacks(created_at);

-- 2. Create activation_payments table if it doesn't exist
CREATE TABLE IF NOT EXISTS activation_payments (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    external_reference TEXT UNIQUE NOT NULL,
    amount DECIMAL(10,2) NOT NULL DEFAULT 500.00,
    status TEXT DEFAULT 'PENDING',
    payhero_response JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    confirmed_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add indexes for activation_payments
CREATE INDEX IF NOT EXISTS idx_activation_payments_user_id ON activation_payments(user_id);
CREATE INDEX IF NOT EXISTS idx_activation_payments_external_ref ON activation_payments(external_reference);
CREATE INDEX IF NOT EXISTS idx_activation_payments_status ON activation_payments(status);

-- 3. Ensure users table has activation fields (add if they don't exist)
ALTER TABLE users 
ADD COLUMN IF NOT EXISTS is_activated BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS activation_date TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS income_wallet DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS recharge_wallet DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_earned DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS withdrawal_account_type TEXT,
ADD COLUMN IF NOT EXISTS withdrawal_account_details TEXT,
ADD COLUMN IF NOT EXISTS onboarding_complete BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS today_earnings DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS yesterday_earnings DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS tasks_completed_today INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS tasks_reset_date DATE;

-- 4. Create transaction function for activation payments
CREATE OR REPLACE FUNCTION record_activation_payment(
    p_user_id UUID,
    p_external_reference TEXT,
    p_amount DECIMAL DEFAULT 500.00
) RETURNS UUID AS $$
DECLARE
    payment_id UUID;
BEGIN
    -- Insert activation payment record
    INSERT INTO activation_payments (user_id, external_reference, amount)
    VALUES (p_user_id, p_external_reference, p_amount)
    RETURNING id INTO payment_id;
    
    RETURN payment_id;
EXCEPTION
    WHEN unique_violation THEN
        -- Payment already exists, return existing ID
        SELECT id INTO payment_id 
        FROM activation_payments 
        WHERE external_reference = p_external_reference;
        RETURN payment_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 5. Update RLS policies for payment tables
ALTER TABLE payment_callbacks ENABLE ROW LEVEL SECURITY;
ALTER TABLE activation_payments ENABLE ROW LEVEL SECURITY;

-- Policies for payment_callbacks (only service role can insert)
CREATE POLICY "Service role can manage payment callbacks" ON payment_callbacks
    FOR ALL USING (auth.role() = 'service_role');

-- Policies for activation_payments
CREATE POLICY "Users can view their own activation payments" ON activation_payments
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Service role can manage activation payments" ON activation_payments
    FOR ALL USING (auth.role() = 'service_role');

-- 6. Create function to distribute referral commissions (if not exists)
CREATE OR REPLACE FUNCTION distribute_referral_commissions(new_user_id UUID)
RETURNS void AS $$
DECLARE
    referrer_id UUID;
    referral_level INTEGER := 1;
    commission_rate DECIMAL;
BEGIN
    -- Get direct referrer
    SELECT referred_by INTO referrer_id
    FROM users
    WHERE id = new_user_id AND referred_by IS NOT NULL;
    
    IF referrer_id IS NULL THEN
        RETURN;
    END IF;
    
    -- Loop through referral levels (up to 5 levels)
    WHILE referrer_id IS NOT NULL AND referral_level <= 5 LOOP
        -- Set commission rates by level
        CASE referral_level
            WHEN 1 THEN commission_rate := 0.40;  -- 40%
            WHEN 2 THEN commission_rate := 0.30;  -- 30%
            WHEN 3 THEN commission_rate := 0.20;  -- 20%
            WHEN 4 THEN commission_rate := 0.10;  -- 10%
            WHEN 5 THEN commission_rate := 0.05;  -- 5%
            ELSE commission_rate := 0;
        END CASE;
        
        -- Add commission to referrer's income wallet
        UPDATE users
        SET income_wallet = income_wallet + (500 * commission_rate),
            total_earned = total_earned + (500 * commission_rate)
        WHERE id = referrer_id;
        
        -- Record commission transaction
        INSERT INTO transactions (
            user_id, 
            type, 
            amount, 
            balance_after, 
            source, 
            description,
            created_at
        )
        SELECT 
            referrer_id,
            'Referral Commission',
            500 * commission_rate,
            income_wallet,
            'Referral System',
            format('Level %s referral commission from user activation', referral_level),
            NOW()
        FROM users
        WHERE id = referrer_id;
        
        -- Get next level referrer
        SELECT referred_by INTO referrer_id
        FROM users
        WHERE id = referrer_id;
        
        referral_level := referral_level + 1;
    END LOOP;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 7. Grant necessary permissions
GRANT ALL ON payment_callbacks TO service_role;
GRANT ALL ON activation_payments TO service_role;
GRANT EXECUTE ON FUNCTION record_activation_payment TO service_role;
GRANT EXECUTE ON FUNCTION distribute_referral_commissions TO service_role;

-- 8. Create updated_at trigger for payment tables
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply triggers
CREATE TRIGGER update_payment_callbacks_updated_at
    BEFORE UPDATE ON payment_callbacks
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_activation_payments_updated_at
    BEFORE UPDATE ON activation_payments
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 9. Verify setup
SELECT 'Payment system setup completed successfully!' as status;

-- [9/9] fix_user_trigger: light daily-stats trigger (replaces heavy one)
-- ====================================================================
-- Fix for slow user profile creation
-- The issue: trigger_update_daily_stats_user runs expensive aggregation queries on every user insert
-- Solution: Remove the trigger or make it async

-- Option 1: Remove the trigger entirely (recommended for now)
DROP TRIGGER IF EXISTS trigger_update_daily_stats_user ON users;

-- Option 2: Create a lighter version that doesn't run expensive queries
CREATE OR REPLACE FUNCTION update_daily_stats_on_user_create_light()
RETURNS TRIGGER AS $$
BEGIN
    -- Just ensure the daily stats record exists, don't refresh expensive calculations
    INSERT INTO daily_statistics (stat_date)
    VALUES (CURRENT_DATE)
    ON CONFLICT (stat_date) DO NOTHING;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create the lighter trigger
CREATE TRIGGER trigger_update_daily_stats_user_light
    AFTER INSERT ON users
    FOR EACH ROW EXECUTE FUNCTION update_daily_stats_on_user_create_light();

-- Note: You can run refresh_daily_statistics() manually or via a cron job
-- instead of on every user creation
